///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.画像比較
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_エビデンスフォルダ作成 recording.
    /// </summary>
    [TestModule("62e7cbb1-8a35-4d7b-b7ce-9c7b7af79621", ModuleType.Recording, 1)]
    public partial class 操作_エビデンスフォルダ作成 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_エビデンスフォルダ作成 instance = new 操作_エビデンスフォルダ作成();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_エビデンスフォルダ作成()
        {
            evidenceFolderPath = "";
            baseEvidenceFolderPath = "";
            resultFolderPath = "";
            baseResultFolderPath = "";
            targetFolderPath = "";
            baseTargetFolderPath = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_エビデンスフォルダ作成 Instance
        {
            get { return instance; }
        }

#region Variables

        string _evidenceFolderPath;

        /// <summary>
        /// Gets or sets the value of variable evidenceFolderPath.
        /// </summary>
        [TestVariable("6eac5a12-203a-4117-9101-e4fb855563be")]
        public string evidenceFolderPath
        {
            get { return _evidenceFolderPath; }
            set { _evidenceFolderPath = value; }
        }

        string _baseEvidenceFolderPath;

        /// <summary>
        /// Gets or sets the value of variable baseEvidenceFolderPath.
        /// </summary>
        [TestVariable("ee09c9d9-abf0-49ea-8f88-b98d1c2fb243")]
        public string baseEvidenceFolderPath
        {
            get { return _baseEvidenceFolderPath; }
            set { _baseEvidenceFolderPath = value; }
        }

        string _resultFolderPath;

        /// <summary>
        /// Gets or sets the value of variable resultFolderPath.
        /// </summary>
        [TestVariable("c9c857f6-fe42-4cee-a70a-b9030518031a")]
        public string resultFolderPath
        {
            get { return _resultFolderPath; }
            set { _resultFolderPath = value; }
        }

        string _baseResultFolderPath;

        /// <summary>
        /// Gets or sets the value of variable baseResultFolderPath.
        /// </summary>
        [TestVariable("2a1e289b-a969-4904-ae19-44542d78b033")]
        public string baseResultFolderPath
        {
            get { return _baseResultFolderPath; }
            set { _baseResultFolderPath = value; }
        }

        string _targetFolderPath;

        /// <summary>
        /// Gets or sets the value of variable targetFolderPath.
        /// </summary>
        [TestVariable("acdf971f-147f-445d-8046-4b39a12b907d")]
        public string targetFolderPath
        {
            get { return _targetFolderPath; }
            set { _targetFolderPath = value; }
        }

        string _baseTargetFolderPath;

        /// <summary>
        /// Gets or sets the value of variable baseTargetFolderPath.
        /// </summary>
        [TestVariable("8d01f429-8171-414d-b834-4df1d7867424")]
        public string baseTargetFolderPath
        {
            get { return _baseTargetFolderPath; }
            set { _baseTargetFolderPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // 画像比較で使用するフォルダパスの作成
            Report.Log(ReportLevel.Info, "Section", "画像比較で使用するフォルダパスの作成", new RecordItemIndex(0));
            
            evidenceFolderPath = UserCode.UserCodeCollection_ImageCompare.GetEvidenceFolderPath(baseEvidenceFolderPath);
            Delay.Milliseconds(0);
            
            resultFolderPath = UserCode.UserCodeCollection_ImageCompare.GetEvidenceFolderPath(baseResultFolderPath);
            Delay.Milliseconds(0);
            
            targetFolderPath = UserCode.UserCodeCollection_ImageCompare.GetTargetFolderPath(baseTargetFolderPath);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", evidenceFolderPath, new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "User", resultFolderPath, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "User", targetFolderPath, new RecordItemIndex(6));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
