///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.画像比較
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_Table領域 recording.
    /// </summary>
    [TestModule("32dcaa59-3e35-4361-80a8-07c3ae465689", ModuleType.Recording, 1)]
    public partial class 確認_Table領域 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.DemoApp repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.DemoApp repo = global::HotelTrainingTest.Repository.DemoApp.Instance;

        static 確認_Table領域 instance = new 確認_Table領域();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_Table領域()
        {
            evidenceFileName = "";
            evidenceFolderPath = "";
            targetName = "";
            fileExtension = "";
            resultFileName = "";
            resultFolderPath = "";
            targetFileName = "";
            targetFolderPath = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_Table領域 Instance
        {
            get { return instance; }
        }

#region Variables

        string _evidenceFileName;

        /// <summary>
        /// Gets or sets the value of variable evidenceFileName.
        /// </summary>
        [TestVariable("5fd01ac7-23e3-4098-bbc9-f1bc1acf6eca")]
        public string evidenceFileName
        {
            get { return _evidenceFileName; }
            set { _evidenceFileName = value; }
        }

        string _evidenceFolderPath;

        /// <summary>
        /// Gets or sets the value of variable evidenceFolderPath.
        /// </summary>
        [TestVariable("f375ed5c-cc72-437c-accd-973ae7b74bf9")]
        public string evidenceFolderPath
        {
            get { return _evidenceFolderPath; }
            set { _evidenceFolderPath = value; }
        }

        string _targetName;

        /// <summary>
        /// Gets or sets the value of variable targetName.
        /// </summary>
        [TestVariable("4f266eab-078b-4905-8c8a-5a98a13e7990")]
        public string targetName
        {
            get { return _targetName; }
            set { _targetName = value; }
        }

        string _fileExtension;

        /// <summary>
        /// Gets or sets the value of variable fileExtension.
        /// </summary>
        [TestVariable("a61ea2fd-5300-42c3-b6ec-d9f4094a77b0")]
        public string fileExtension
        {
            get { return _fileExtension; }
            set { _fileExtension = value; }
        }

        string _resultFileName;

        /// <summary>
        /// Gets or sets the value of variable resultFileName.
        /// </summary>
        [TestVariable("5b1ff985-6b19-447a-a444-70ce30279a3f")]
        public string resultFileName
        {
            get { return _resultFileName; }
            set { _resultFileName = value; }
        }

        string _resultFolderPath;

        /// <summary>
        /// Gets or sets the value of variable resultFolderPath.
        /// </summary>
        [TestVariable("d0116f07-dcaa-43bc-b58f-a87ae4104880")]
        public string resultFolderPath
        {
            get { return _resultFolderPath; }
            set { _resultFolderPath = value; }
        }

        string _targetFileName;

        /// <summary>
        /// Gets or sets the value of variable targetFileName.
        /// </summary>
        [TestVariable("5478a3e2-0f45-447b-9592-b75eb958ee67")]
        public string targetFileName
        {
            get { return _targetFileName; }
            set { _targetFileName = value; }
        }

        string _targetFolderPath;

        /// <summary>
        /// Gets or sets the value of variable targetFolderPath.
        /// </summary>
        [TestVariable("616dd98a-4bfa-42a6-995f-b3c7b44cf49f")]
        public string targetFolderPath
        {
            get { return _targetFolderPath; }
            set { _targetFolderPath = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable rowIndex.
        /// </summary>
        [TestVariable("cc3a9758-5575-4028-a8bf-2d17d8b30c6f")]
        public string rowIndex
        {
            get { return repo.rowIndex; }
            set { repo.rowIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable colIndex.
        /// </summary>
        [TestVariable("b6065002-ab43-4bff-beea-aafbdf8a75eb")]
        public string colIndex
        {
            get { return repo.colIndex; }
            set { repo.colIndex = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // UI-elementタブのTable領域(一部除外)の画像比較をエビデンスフォルダ作成で作成したフォルダパスを使用する
            Report.Log(ReportLevel.Info, "Section", "UI-elementタブのTable領域(一部除外)の画像比較をエビデンスフォルダ作成で作成したフォルダパスを使用する", new RecordItemIndex(0));
            
            UserCode.UserCodeCollection_ImageCompare.InitializationIgnoreRectangles();
            Delay.Milliseconds(0);
            
            evidenceFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(evidenceFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            resultFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(resultFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            targetFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(targetFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection_ImageCompare.GetScreenshot(repo.RxDemoApp.タブ関連.UI_elementタブ.SelfInfo, evidenceFileName);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection_ImageCompare.AddIgnoreRectTableInitWin(ValueConverter.ArgumentFromString<int>("startRowIndex", "2"), ValueConverter.ArgumentFromString<int>("startColIndex", "3"), ValueConverter.ArgumentFromString<int>("endRowIndex", "4"), ValueConverter.ArgumentFromString<int>("endColIndex", "5"), repo.RxDemoApp.タブ関連.UI_elementタブ.table_除外領域Info, repo.RxDemoApp.タブ関連.UI_elementタブ.SelfInfo);
            Delay.Milliseconds(0);
            
            try {
                UserCode.UserCodeCollection_ImageCompare.ValidateCompareImageBitmapIgnore(evidenceFileName, targetFileName, resultFileName);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
