///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.追加課題
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_任意のファイルダウンロード recording.
    /// </summary>
    [TestModule("6030311c-d824-4930-8fcb-bfe62ebf315b", ModuleType.Recording, 1)]
    public partial class 操作_任意のファイルダウンロード : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_任意のファイルダウンロード instance = new 操作_任意のファイルダウンロード();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_任意のファイルダウンロード()
        {
            evidenceFileName = "";
            evidenceFolderPath = "";
            targetName = "";
            fileExtension = "";
            resultFileName = "";
            resultFolderPath = "";
            targetFileName = "";
            targetFolderPath = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_任意のファイルダウンロード Instance
        {
            get { return instance; }
        }

#region Variables

        string _evidenceFileName;

        /// <summary>
        /// Gets or sets the value of variable evidenceFileName.
        /// </summary>
        [TestVariable("1ef23713-5975-43e5-a60d-0e2aa6fe3746")]
        public string evidenceFileName
        {
            get { return _evidenceFileName; }
            set { _evidenceFileName = value; }
        }

        string _evidenceFolderPath;

        /// <summary>
        /// Gets or sets the value of variable evidenceFolderPath.
        /// </summary>
        [TestVariable("aa5e5b1d-8e90-48e6-8db4-25abd0b087a8")]
        public string evidenceFolderPath
        {
            get { return _evidenceFolderPath; }
            set { _evidenceFolderPath = value; }
        }

        string _targetName;

        /// <summary>
        /// Gets or sets the value of variable targetName.
        /// </summary>
        [TestVariable("5f0b864a-1442-4bb5-8ed3-49f3fde705b2")]
        public string targetName
        {
            get { return _targetName; }
            set { _targetName = value; }
        }

        string _fileExtension;

        /// <summary>
        /// Gets or sets the value of variable fileExtension.
        /// </summary>
        [TestVariable("60eb601f-1979-4e2e-8a03-047478cf02a4")]
        public string fileExtension
        {
            get { return _fileExtension; }
            set { _fileExtension = value; }
        }

        string _resultFileName;

        /// <summary>
        /// Gets or sets the value of variable resultFileName.
        /// </summary>
        [TestVariable("4aadbd6c-f6e8-4534-bbe7-c51f49302f5b")]
        public string resultFileName
        {
            get { return _resultFileName; }
            set { _resultFileName = value; }
        }

        string _resultFolderPath;

        /// <summary>
        /// Gets or sets the value of variable resultFolderPath.
        /// </summary>
        [TestVariable("d66e1de9-616a-45f9-8d12-e671a972d1c4")]
        public string resultFolderPath
        {
            get { return _resultFolderPath; }
            set { _resultFolderPath = value; }
        }

        string _targetFileName;

        /// <summary>
        /// Gets or sets the value of variable targetFileName.
        /// </summary>
        [TestVariable("34086884-38ec-4174-8538-3891443ca4a1")]
        public string targetFileName
        {
            get { return _targetFileName; }
            set { _targetFileName = value; }
        }

        string _targetFolderPath;

        /// <summary>
        /// Gets or sets the value of variable targetFolderPath.
        /// </summary>
        [TestVariable("a60bbf7a-7a54-46ab-ae7c-88ac950d7824")]
        public string targetFolderPath
        {
            get { return _targetFolderPath; }
            set { _targetFolderPath = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable fileName.
        /// </summary>
        [TestVariable("6ed3c54e-582c-4eb0-a18b-a83bc40af209")]
        public string fileName
        {
            get { return repo.fileName; }
            set { repo.fileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            evidenceFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(evidenceFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            targetFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(targetFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item '追加課題_ファイルダウンロード.link_任意のファイル' at Center.", repo.追加課題_ファイルダウンロード.link_任意のファイルInfo, new RecordItemIndex(2));
            repo.追加課題_ファイルダウンロード.link_任意のファイル.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'Hotelサイト.ダイアログ_名前を付けて保存'", repo.Hotelサイト.ダイアログ_名前を付けて保存.SelfInfo, new ActionTimeout(5000), new RecordItemIndex(3));
            repo.Hotelサイト.ダイアログ_名前を付けて保存.SelfInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$evidenceFileName' on item 'Hotelサイト.ダイアログ_名前を付けて保存.textbox_ファイル名'.", repo.Hotelサイト.ダイアログ_名前を付けて保存.textbox_ファイル名Info, new RecordItemIndex(4));
            repo.Hotelサイト.ダイアログ_名前を付けて保存.textbox_ファイル名.Element.SetAttributeValue("Text", evidenceFileName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.ダイアログ_名前を付けて保存.button_保存' at Center.", repo.Hotelサイト.ダイアログ_名前を付けて保存.button_保存Info, new RecordItemIndex(5));
            repo.Hotelサイト.ダイアログ_名前を付けて保存.button_保存.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded('5000ms') on item '追加課題_ファイルダウンロード'.", repo.追加課題_ファイルダウンロード.SelfInfo, new RecordItemIndex(6));
            repo.追加課題_ファイルダウンロード.Self.WaitForDocumentLoaded(ValueConverter.ArgumentFromString<Ranorex.Duration>("timeout", "5000ms"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
