///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.追加課題
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_ブラウザ起動_追加課題 recording.
    /// </summary>
    [TestModule("eb70a7da-d975-4c4b-87d1-dbaf7026579c", ModuleType.Recording, 1)]
    public partial class 操作_ブラウザ起動_追加課題 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_ブラウザ起動_追加課題 instance = new 操作_ブラウザ起動_追加課題();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_ブラウザ起動_追加課題()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_ブラウザ起動_追加課題 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // 操作_ブラウザを起動する
            Report.Log(ReportLevel.Info, "Section", "操作_ブラウザを起動する", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://the-internet.herokuapp.com/' in maximized mode.", new RecordItemIndex(1));
            Host.Current.OpenBrowser("https://the-internet.herokuapp.com/", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded('5000ms') on item '追加課題_共通'.", repo.追加課題_共通.SelfInfo, new RecordItemIndex(2));
            repo.追加課題_共通.Self.WaitForDocumentLoaded(ValueConverter.ArgumentFromString<Ranorex.Duration>("timeout", "5000ms"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
