///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.追加課題
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_テキストファイル recording.
    /// </summary>
    [TestModule("d11bebf1-53e6-4f3b-be97-5e26c4e3acc8", ModuleType.Recording, 1)]
    public partial class 確認_テキストファイル : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_テキストファイル instance = new 確認_テキストファイル();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_テキストファイル()
        {
            evidenceFileName = "";
            targetFileName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_テキストファイル Instance
        {
            get { return instance; }
        }

#region Variables

        string _evidenceFileName;

        /// <summary>
        /// Gets or sets the value of variable evidenceFileName.
        /// </summary>
        [TestVariable("89148f94-650f-4c34-8682-c4a7e21631d7")]
        public string evidenceFileName
        {
            get { return _evidenceFileName; }
            set { _evidenceFileName = value; }
        }

        string _targetFileName;

        /// <summary>
        /// Gets or sets the value of variable targetFileName.
        /// </summary>
        [TestVariable("08bb11e8-bbf2-493f-9195-126c666ef6ad")]
        public string targetFileName
        {
            get { return _targetFileName; }
            set { _targetFileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                UserCode.UserCodeCollection_textCompare.ValidateFilesTextEqual(evidenceFileName, targetFileName, "UTF-8");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
