///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Demoアプリ.Test_database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The データソースフィルタ_リスト確認 recording.
    /// </summary>
    [TestModule("29b2f355-814a-456a-be9c-b2df1f0f3dbb", ModuleType.Recording, 1)]
    public partial class データソースフィルタ_リスト確認 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static データソースフィルタ_リスト確認 instance = new データソースフィルタ_リスト確認();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public データソースフィルタ_リスト確認()
        {
            id = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static データソースフィルタ_リスト確認 Instance
        {
            get { return instance; }
        }

#region Variables

        string _id;

        /// <summary>
        /// Gets or sets the value of variable id.
        /// </summary>
        [TestVariable("9ef5d47d-aec0-4885-adbb-64f99c2a3e31")]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCode.UserCodeCollection.DataFilter("リスト検証", id, "id");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
