///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Demoアプリ.Test_database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_情報入力 recording.
    /// </summary>
    [TestModule("dc590ff6-371b-48f5-8b37-62f8d2fc21a5", ModuleType.Recording, 1)]
    public partial class 操作_情報入力 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.DemoApp repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.DemoApp repo = global::HotelTrainingTest.Repository.DemoApp.Instance;

        static 操作_情報入力 instance = new 操作_情報入力();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_情報入力()
        {
            firstName = "";
            lastName = "";
            department = "";
            age = "";
            gendetType = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_情報入力 Instance
        {
            get { return instance; }
        }

#region Variables

        string _firstName;

        /// <summary>
        /// Gets or sets the value of variable firstName.
        /// </summary>
        [TestVariable("f9f58eac-855d-4169-9b3a-afc8a1e0be4c")]
        public string firstName
        {
            get { return _firstName; }
            set { _firstName = value; }
        }

        string _lastName;

        /// <summary>
        /// Gets or sets the value of variable lastName.
        /// </summary>
        [TestVariable("14200b5e-e118-408c-ad29-c479d84d7f78")]
        public string lastName
        {
            get { return _lastName; }
            set { _lastName = value; }
        }

        string _department;

        /// <summary>
        /// Gets or sets the value of variable department.
        /// </summary>
        [TestVariable("63affbe0-b488-4d4d-9724-c5f717ace93a")]
        public string department
        {
            get { return _department; }
            set { _department = value; }
        }

        string _age;

        /// <summary>
        /// Gets or sets the value of variable age.
        /// </summary>
        [TestVariable("258b3fbf-c7c5-4b86-a800-8e5ee7a70cef")]
        public string age
        {
            get { return _age; }
            set { _age = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable gendetType.
        /// </summary>
        [TestVariable("b60cdcb5-f0e1-4aec-add6-f4908e26e84c")]
        public string gendetType
        {
            get { return repo.gendetType; }
            set { repo.gendetType = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCode.UserCodeCollection.InputIfIsNotIgnore_WindowsApp(repo.RxDemoApp.タブ関連.Test_databaseタブ.text_FirstnameInfo, firstName);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore_WindowsApp(repo.RxDemoApp.タブ関連.Test_databaseタブ.text_LastnameInfo, lastName);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore_WindowsApp(repo.RxDemoApp.タブ関連.Test_databaseタブ.select_DepartmentInfo, department);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore_WindowsApp(repo.RxDemoApp.タブ関連.Test_databaseタブ.text_AgeInfo, age);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore_WindowsApp(repo.RxDemoApp.タブ関連.Test_databaseタブ.radio_GenderInfo, gendetType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxDemoApp.タブ関連.Test_databaseタブ.button_Add_entry' at Center.", repo.RxDemoApp.タブ関連.Test_databaseタブ.button_Add_entryInfo, new RecordItemIndex(5));
            repo.RxDemoApp.タブ関連.Test_databaseタブ.button_Add_entry.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
