///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Demoアプリ.Test_database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_登録者リスト recording.
    /// </summary>
    [TestModule("49f4154d-bd72-4865-8783-0e11349c49b0", ModuleType.Recording, 1)]
    public partial class 確認_登録者リスト : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.DemoApp repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.DemoApp repo = global::HotelTrainingTest.Repository.DemoApp.Instance;

        static 確認_登録者リスト instance = new 確認_登録者リスト();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_登録者リスト()
        {
            evidenceFileName = "";
            evidenceFolderPath = "";
            targetName = "";
            fileExtension = "";
            resultFileName = "";
            resultFolderPath = "";
            targetFileName = "";
            targetFolderPath = "";
            numberOfEntries = "yourValue";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_登録者リスト Instance
        {
            get { return instance; }
        }

#region Variables

        string _evidenceFileName;

        /// <summary>
        /// Gets or sets the value of variable evidenceFileName.
        /// </summary>
        [TestVariable("156888ff-470d-4a6c-bb38-f02603cf5d2e")]
        public string evidenceFileName
        {
            get { return _evidenceFileName; }
            set { _evidenceFileName = value; }
        }

        string _evidenceFolderPath;

        /// <summary>
        /// Gets or sets the value of variable evidenceFolderPath.
        /// </summary>
        [TestVariable("f3f14365-5e77-47ac-bd7b-cb6156db84be")]
        public string evidenceFolderPath
        {
            get { return _evidenceFolderPath; }
            set { _evidenceFolderPath = value; }
        }

        string _targetName;

        /// <summary>
        /// Gets or sets the value of variable targetName.
        /// </summary>
        [TestVariable("0d11c454-f312-4a48-822d-6f7e2fca1bfc")]
        public string targetName
        {
            get { return _targetName; }
            set { _targetName = value; }
        }

        string _fileExtension;

        /// <summary>
        /// Gets or sets the value of variable fileExtension.
        /// </summary>
        [TestVariable("e0fb9671-2a46-4262-bc6d-8b73d079a98a")]
        public string fileExtension
        {
            get { return _fileExtension; }
            set { _fileExtension = value; }
        }

        string _resultFileName;

        /// <summary>
        /// Gets or sets the value of variable resultFileName.
        /// </summary>
        [TestVariable("81836253-fd35-4695-aaf8-ce9fe33a1f35")]
        public string resultFileName
        {
            get { return _resultFileName; }
            set { _resultFileName = value; }
        }

        string _resultFolderPath;

        /// <summary>
        /// Gets or sets the value of variable resultFolderPath.
        /// </summary>
        [TestVariable("42a48d04-fac4-4a4c-bb99-06ed858d88c9")]
        public string resultFolderPath
        {
            get { return _resultFolderPath; }
            set { _resultFolderPath = value; }
        }

        string _targetFileName;

        /// <summary>
        /// Gets or sets the value of variable targetFileName.
        /// </summary>
        [TestVariable("96699ef7-a2f0-4522-9641-82bc40a5b7e1")]
        public string targetFileName
        {
            get { return _targetFileName; }
            set { _targetFileName = value; }
        }

        string _targetFolderPath;

        /// <summary>
        /// Gets or sets the value of variable targetFolderPath.
        /// </summary>
        [TestVariable("7f3fe599-dd74-40ed-8716-587d5102abc1")]
        public string targetFolderPath
        {
            get { return _targetFolderPath; }
            set { _targetFolderPath = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable numberOfEntries.
        /// </summary>
        [TestVariable("bc7d1bd6-3f1c-47b8-9b3f-79e5f0b923f7")]
        public string numberOfEntries
        {
            get { return repo.numberOfEntries; }
            set { repo.numberOfEntries = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text=$numberOfEntries) on item 'RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entries'.", repo.RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entriesInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entriesInfo, "Text", numberOfEntries, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            evidenceFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(evidenceFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            resultFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(resultFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            targetFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(targetFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection_ImageCompare.GetScreenshot(repo.RxDemoApp.タブ関連.Test_databaseタブ.SelfInfo, evidenceFileName);
            Delay.Milliseconds(0);
            
            try {
                UserCode.UserCodeCollection_ImageCompare.ValidateCompareImageBitmapIgnore(evidenceFileName, targetFileName, resultFileName);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
