///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Demoアプリ.Test_database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_登録人数_リスト内容 recording.
    /// </summary>
    [TestModule("d9e87ee0-454d-439c-b898-79c9fd7c56be", ModuleType.Recording, 1)]
    public partial class 確認_登録人数_リスト内容 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.DemoApp repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.DemoApp repo = global::HotelTrainingTest.Repository.DemoApp.Instance;

        static 確認_登録人数_リスト内容 instance = new 確認_登録人数_リスト内容();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_登録人数_リスト内容()
        {
            numberOfEntries = "yourValue";
            personList = "yourValue";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_登録人数_リスト内容 Instance
        {
            get { return instance; }
        }

#region Variables

        string _personList;

        /// <summary>
        /// Gets or sets the value of variable personList.
        /// </summary>
        [TestVariable("224021c3-3df2-4d4d-8275-5faa885edae1")]
        public string personList
        {
            get { return _personList; }
            set { _personList = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable numberOfEntries.
        /// </summary>
        [TestVariable("69418956-019b-4b3c-b4f2-61d988c64c22")]
        public string numberOfEntries
        {
            get { return repo.numberOfEntries; }
            set { repo.numberOfEntries = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text=$numberOfEntries) on item 'RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entries'.", repo.RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entriesInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entriesInfo, "Text", numberOfEntries, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text=$personList) on item 'RxDemoApp.タブ関連.Test_databaseタブ.list_PersonList'.", repo.RxDemoApp.タブ関連.Test_databaseタブ.list_PersonListInfo, new RecordItemIndex(1));
                Validate.AttributeEqual(repo.RxDemoApp.タブ関連.Test_databaseタブ.list_PersonListInfo, "Text", personList, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxDemoApp.タブ関連.Test_databaseタブ.list_PersonList' at Center.", repo.RxDemoApp.タブ関連.Test_databaseタブ.list_PersonListInfo, new RecordItemIndex(2));
            repo.RxDemoApp.タブ関連.Test_databaseタブ.list_PersonList.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxDemoApp.タブ関連.Test_databaseタブ.button_Delete_entry' at Center.", repo.RxDemoApp.タブ関連.Test_databaseタブ.button_Delete_entryInfo, new RecordItemIndex(3));
            repo.RxDemoApp.タブ関連.Test_databaseタブ.button_Delete_entry.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Text' to equal the specified value '0'. Associated repository item: 'RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entries'", repo.RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entriesInfo, new RecordItemIndex(4));
            repo.RxDemoApp.タブ関連.Test_databaseタブ.label_Number_of_entriesInfo.WaitForAttributeEqual(5000, "Text", "0");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
