///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Demoアプリ.Test_database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_リスト登録内容 recording.
    /// </summary>
    [TestModule("6ea75f8d-a6b2-4ad6-9d4a-102375444813", ModuleType.Recording, 1)]
    public partial class 確認_リスト登録内容 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_リスト登録内容 instance = new 確認_リスト登録内容();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_リスト登録内容()
        {
            personList = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_リスト登録内容 Instance
        {
            get { return instance; }
        }

#region Variables

        string _personList;

        /// <summary>
        /// Gets or sets the value of variable personList.
        /// </summary>
        [TestVariable("3c2f037d-6c21-4841-a0dc-f7ec905442cd")]
        public string personList
        {
            get { return _personList; }
            set { _personList = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable numberOfEntries.
        /// </summary>
        [TestVariable("b479760e-30a2-4858-acba-f19e01086fa5")]
        public string numberOfEntries
        {
            get { return repo.numberOfEntries; }
            set { repo.numberOfEntries = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$personList) on item 'RxDemoApp.タブ関連.Test_databaseタブ.list_PersonList'.", repo.RxDemoApp.タブ関連.Test_databaseタブ.list_PersonListInfo, new RecordItemIndex(0));
                Validate.AttributeContains(repo.RxDemoApp.タブ関連.Test_databaseタブ.list_PersonListInfo, "Text", personList, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
