///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.ログイン
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_ログイン recording.
    /// </summary>
    [TestModule("4d72fe0c-a960-4cbe-bc95-ccabbb47a96b", ModuleType.Recording, 1)]
    public partial class 操作_ログイン : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_ログイン instance = new 操作_ログイン();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_ログイン()
        {
            email = "yourValue";
            password = "(null)";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_ログイン Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("976f0928-dd01-49bd-80dd-36738e5f4284")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("905e2266-c5d3-4582-af24-4765384748ba")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.Hotel_共通.共通動作.link_ログイン' at Center.", repo.Hotelサイト.Hotel_共通.共通動作.link_ログインInfo, new RecordItemIndex(0));
            repo.Hotelサイト.Hotel_共通.共通動作.link_ログイン.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded('5000ms') on item 'Hotelサイト.Hotel_共通'.", repo.Hotelサイト.Hotel_共通.SelfInfo, new RecordItemIndex(1));
            repo.Hotelサイト.Hotel_共通.Self.WaitForDocumentLoaded(ValueConverter.ArgumentFromString<Ranorex.Duration>("timeout", "5000ms"));
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_ログイン画面.textbox_メールアドレスInfo, email);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_ログイン画面.textbox_パスワードInfo, password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.Hotel_ログイン画面.button_ログイン' at Center.", repo.Hotelサイト.Hotel_ログイン画面.button_ログインInfo, new RecordItemIndex(4));
            repo.Hotelサイト.Hotel_ログイン画面.button_ログイン.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded('5000ms') on item 'Hotelサイト.Hotel_共通'.", repo.Hotelサイト.Hotel_共通.SelfInfo, new RecordItemIndex(5));
            repo.Hotelサイト.Hotel_共通.Self.WaitForDocumentLoaded(ValueConverter.ArgumentFromString<Ranorex.Duration>("timeout", "5000ms"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
