///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.ログイン
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_ログイン情報入力 recording.
    /// </summary>
    [TestModule("830c9925-e47b-43a9-b051-5643ef754cc1", ModuleType.Recording, 1)]
    public partial class 操作_ログイン情報入力 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_ログイン情報入力 instance = new 操作_ログイン情報入力();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_ログイン情報入力()
        {
            email = "yourValue";
            password = "(null)";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_ログイン情報入力 Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("a434861a-550d-4bf3-83ff-755a3e016a60")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("265dd5e7-b7ac-464c-a1b5-d1f9f4d5f191")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$email' on item 'Hotelサイト.Hotel_ログイン画面.textbox_メールアドレス'.", repo.Hotelサイト.Hotel_ログイン画面.textbox_メールアドレスInfo, new RecordItemIndex(0));
            repo.Hotelサイト.Hotel_ログイン画面.textbox_メールアドレス.Element.SetAttributeValue("Value", email);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$password' on item 'Hotelサイト.Hotel_ログイン画面.textbox_パスワード'.", repo.Hotelサイト.Hotel_ログイン画面.textbox_パスワードInfo, new RecordItemIndex(1));
            repo.Hotelサイト.Hotel_ログイン画面.textbox_パスワード.Element.SetAttributeValue("Value", password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.Hotel_ログイン画面.button_ログイン' at Center.", repo.Hotelサイト.Hotel_ログイン画面.button_ログインInfo, new RecordItemIndex(2));
            repo.Hotelサイト.Hotel_ログイン画面.button_ログイン.Click();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Invoke action", "(Optional Action)\r\nInvoking WaitForDocumentLoaded('5000ms') on item 'Hotelサイト.Hotel_共通'.", repo.Hotelサイト.Hotel_共通.SelfInfo, new RecordItemIndex(3));
                repo.Hotelサイト.Hotel_共通.Self.WaitForDocumentLoaded(ValueConverter.ArgumentFromString<Ranorex.Duration>("timeout", "5000ms"));
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
