///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.ログイン
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_メールアドレス_エラーメッセージ recording.
    /// </summary>
    [TestModule("63e7fa2c-9e8a-44e0-8c92-0dfd32378768", ModuleType.Recording, 1)]
    public partial class 確認_メールアドレス_エラーメッセージ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_メールアドレス_エラーメッセージ instance = new 確認_メールアドレス_エラーメッセージ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_メールアドレス_エラーメッセージ()
        {
            email_message = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_メールアドレス_エラーメッセージ Instance
        {
            get { return instance; }
        }

#region Variables

        string _email_message;

        /// <summary>
        /// Gets or sets the value of variable email_message.
        /// </summary>
        [TestVariable("e1c57fbb-7644-4ed8-8b75-191096cca677")]
        public string email_message
        {
            get { return _email_message; }
            set { _email_message = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$email_message) on item 'Hotelサイト.Hotel_ログイン画面.label_メールアドレス_エラーメッセージ'.", repo.Hotelサイト.Hotel_ログイン画面.label_メールアドレス_エラーメッセージInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_ログイン画面.label_メールアドレス_エラーメッセージInfo, "InnerText", email_message, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
