///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.ログイン
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_ログイン後の画面 recording.
    /// </summary>
    [TestModule("a53ceb5d-530c-4d88-8b10-bec55c370f12", ModuleType.Recording, 1)]
    public partial class 確認_ログイン後の画面 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_ログイン後の画面 instance = new 確認_ログイン後の画面();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_ログイン後の画面()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_ログイン後の画面 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_共通.共通動作.link_マイページ'.", repo.Hotelサイト.Hotel_共通.共通動作.link_マイページInfo, new RecordItemIndex(0));
                Validate.Exists(repo.Hotelサイト.Hotel_共通.共通動作.link_マイページInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating NotExists on item 'Hotelサイト.Hotel_共通.共通動作.link_会員登録'.", repo.Hotelサイト.Hotel_共通.共通動作.link_会員登録Info, new RecordItemIndex(1));
                Validate.NotExists(repo.Hotelサイト.Hotel_共通.共通動作.link_会員登録Info, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_共通.共通動作.button_ログアウト'.", repo.Hotelサイト.Hotel_共通.共通動作.button_ログアウトInfo, new RecordItemIndex(2));
                Validate.Exists(repo.Hotelサイト.Hotel_共通.共通動作.button_ログアウトInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating NotExists on item 'Hotelサイト.Hotel_共通.共通動作.link_ログイン'.", repo.Hotelサイト.Hotel_共通.共通動作.link_ログインInfo, new RecordItemIndex(3));
                Validate.NotExists(repo.Hotelサイト.Hotel_共通.共通動作.link_ログインInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
