///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Demoアプリ.Introduction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_メッセージ内容 recording.
    /// </summary>
    [TestModule("4c3f8d06-e6bc-4512-9e30-ada239b0bc39", ModuleType.Recording, 1)]
    public partial class 確認_メッセージ内容 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.DemoApp repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.DemoApp repo = global::HotelTrainingTest.Repository.DemoApp.Instance;

        static 確認_メッセージ内容 instance = new 確認_メッセージ内容();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_メッセージ内容()
        {
            checkMessage = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_メッセージ内容 Instance
        {
            get { return instance; }
        }

#region Variables

        string _checkMessage;

        /// <summary>
        /// Gets or sets the value of variable checkMessage.
        /// </summary>
        [TestVariable("8a8f4a66-a142-49a7-8833-758ee1dc4d26")]
        public string checkMessage
        {
            get { return _checkMessage; }
            set { _checkMessage = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text=$checkMessage) on item 'RxDemoApp.タブ関連.Introductionタブ.label_Welcome'.", repo.RxDemoApp.タブ関連.Introductionタブ.label_WelcomeInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.RxDemoApp.タブ関連.Introductionタブ.label_WelcomeInfo, "Text", checkMessage, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxDemoApp.タブ関連.Introductionタブ.link_Reset' at Center.", repo.RxDemoApp.タブ関連.Introductionタブ.link_ResetInfo, new RecordItemIndex(1));
            repo.RxDemoApp.タブ関連.Introductionタブ.link_Reset.Click();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='Welcome!') on item 'RxDemoApp.タブ関連.Introductionタブ.label_Welcome'.", repo.RxDemoApp.タブ関連.Introductionタブ.label_WelcomeInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.RxDemoApp.タブ関連.Introductionタブ.label_WelcomeInfo, "Text", "Welcome!", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
