///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.マイページ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_会員登録成功 recording.
    /// </summary>
    [TestModule("2b812bcd-2979-4684-8282-af66379cd4d7", ModuleType.Recording, 1)]
    public partial class 確認_会員登録成功 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_会員登録成功 instance = new 確認_会員登録成功();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_会員登録成功()
        {
            check_email = "";
            check_username = "";
            check_rank = "";
            check_address = "";
            check_tel = "";
            check_gender = "";
            check_birthday = "";
            check_notification = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_会員登録成功 Instance
        {
            get { return instance; }
        }

#region Variables

        string _check_email;

        /// <summary>
        /// Gets or sets the value of variable check_email.
        /// </summary>
        [TestVariable("7e66c553-dbb1-4368-8179-d355673b617b")]
        public string check_email
        {
            get { return _check_email; }
            set { _check_email = value; }
        }

        string _check_username;

        /// <summary>
        /// Gets or sets the value of variable check_username.
        /// </summary>
        [TestVariable("c6aa4ea8-f255-4d7e-8ae6-0248a21a1743")]
        public string check_username
        {
            get { return _check_username; }
            set { _check_username = value; }
        }

        string _check_rank;

        /// <summary>
        /// Gets or sets the value of variable check_rank.
        /// </summary>
        [TestVariable("070646b9-b6bb-4f80-9f76-4ea8bfdf9522")]
        public string check_rank
        {
            get { return _check_rank; }
            set { _check_rank = value; }
        }

        string _check_address;

        /// <summary>
        /// Gets or sets the value of variable check_address.
        /// </summary>
        [TestVariable("f4400bba-63f7-492f-a686-7985cc2ced9a")]
        public string check_address
        {
            get { return _check_address; }
            set { _check_address = value; }
        }

        string _check_tel;

        /// <summary>
        /// Gets or sets the value of variable check_tel.
        /// </summary>
        [TestVariable("8650bc6e-39a6-4df0-9967-5b2b96eabb79")]
        public string check_tel
        {
            get { return _check_tel; }
            set { _check_tel = value; }
        }

        string _check_gender;

        /// <summary>
        /// Gets or sets the value of variable check_gender.
        /// </summary>
        [TestVariable("b1b97786-6ecf-4818-b464-c45a2088ad99")]
        public string check_gender
        {
            get { return _check_gender; }
            set { _check_gender = value; }
        }

        string _check_birthday;

        /// <summary>
        /// Gets or sets the value of variable check_birthday.
        /// </summary>
        [TestVariable("5ae352fd-4e68-48c3-9fba-d1fbd513c094")]
        public string check_birthday
        {
            get { return _check_birthday; }
            set { _check_birthday = value; }
        }

        string _check_notification;

        /// <summary>
        /// Gets or sets the value of variable check_notification.
        /// </summary>
        [TestVariable("7eeededa-28fe-4ed2-a8db-89fffa38d27a")]
        public string check_notification
        {
            get { return _check_notification; }
            set { _check_notification = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_マイページ画面'.", repo.Hotelサイト.Hotel_マイページ画面.SelfInfo, new RecordItemIndex(0));
                Validate.Exists(repo.Hotelサイト.Hotel_マイページ画面.SelfInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_共通.共通動作.link_ホーム'.", repo.Hotelサイト.Hotel_共通.共通動作.link_ホームInfo, new RecordItemIndex(1));
                Validate.Exists(repo.Hotelサイト.Hotel_共通.共通動作.link_ホームInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_共通.共通動作.link_宿泊予約'.", repo.Hotelサイト.Hotel_共通.共通動作.link_宿泊予約Info, new RecordItemIndex(2));
                Validate.Exists(repo.Hotelサイト.Hotel_共通.共通動作.link_宿泊予約Info, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_共通.共通動作.link_マイページ'.", repo.Hotelサイト.Hotel_共通.共通動作.link_マイページInfo, new RecordItemIndex(3));
                Validate.Exists(repo.Hotelサイト.Hotel_共通.共通動作.link_マイページInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_共通.共通動作.button_ログアウト'.", repo.Hotelサイト.Hotel_共通.共通動作.button_ログアウトInfo, new RecordItemIndex(4));
                Validate.Exists(repo.Hotelサイト.Hotel_共通.共通動作.button_ログアウトInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_email) on item 'Hotelサイト.Hotel_マイページ画面.label_メールアドレス'.", repo.Hotelサイト.Hotel_マイページ画面.label_メールアドレスInfo, new RecordItemIndex(5));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_マイページ画面.label_メールアドレスInfo, "InnerText", check_email, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_username) on item 'Hotelサイト.Hotel_マイページ画面.label_氏名'.", repo.Hotelサイト.Hotel_マイページ画面.label_氏名Info, new RecordItemIndex(6));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_マイページ画面.label_氏名Info, "InnerText", check_username, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_rank) on item 'Hotelサイト.Hotel_マイページ画面.label_会員ランク'.", repo.Hotelサイト.Hotel_マイページ画面.label_会員ランクInfo, new RecordItemIndex(7));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_マイページ画面.label_会員ランクInfo, "InnerText", check_rank, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_address) on item 'Hotelサイト.Hotel_マイページ画面.label_住所'.", repo.Hotelサイト.Hotel_マイページ画面.label_住所Info, new RecordItemIndex(8));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_マイページ画面.label_住所Info, "InnerText", check_address, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_tel) on item 'Hotelサイト.Hotel_マイページ画面.label_電話番号'.", repo.Hotelサイト.Hotel_マイページ画面.label_電話番号Info, new RecordItemIndex(9));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_マイページ画面.label_電話番号Info, "InnerText", check_tel, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_gender) on item 'Hotelサイト.Hotel_マイページ画面.label_性別'.", repo.Hotelサイト.Hotel_マイページ画面.label_性別Info, new RecordItemIndex(10));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_マイページ画面.label_性別Info, "InnerText", check_gender, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_birthday) on item 'Hotelサイト.Hotel_マイページ画面.label_生年月日'.", repo.Hotelサイト.Hotel_マイページ画面.label_生年月日Info, new RecordItemIndex(11));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_マイページ画面.label_生年月日Info, "InnerText", check_birthday, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_notification) on item 'Hotelサイト.Hotel_マイページ画面.label_お知らせ'.", repo.Hotelサイト.Hotel_マイページ画面.label_お知らせInfo, new RecordItemIndex(12));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_マイページ画面.label_お知らせInfo, "InnerText", check_notification, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(12)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
