///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_可変プラン名予約ボタン押下 recording.
    /// </summary>
    [TestModule("c5b04cd3-110e-4134-bee7-bf71ef538e33", ModuleType.Recording, 1)]
    public partial class 操作_可変プラン名予約ボタン押下 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_可変プラン名予約ボタン押下 instance = new 操作_可変プラン名予約ボタン押下();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_可変プラン名予約ボタン押下()
        {
            planName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_可変プラン名予約ボタン押下 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable planName.
        /// </summary>
        [TestVariable("a45d6c7a-19d8-4e0d-bc46-226847217fe5")]
        public string planName
        {
            get { return repo.planName; }
            set { repo.planName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.Hotel_宿泊予約.link_予約_可変名' at Center.", repo.Hotelサイト.Hotel_宿泊予約.link_予約_可変名Info, new RecordItemIndex(0));
            repo.Hotelサイト.Hotel_宿泊予約.link_予約_可変名.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'InnerText' to contain the specified value $planName. Associated repository item: 'Hotelサイト.Hotel_予約画面.label_プラン名'", repo.Hotelサイト.Hotel_予約画面.label_プラン名Info, new RecordItemIndex(1));
            repo.Hotelサイト.Hotel_予約画面.label_プラン名Info.WaitForAttributeContains(5000, "InnerText", planName);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
