///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_宿泊プラン_一般会員 recording.
    /// </summary>
    [TestModule("31b6b73a-bfe5-4922-8348-20d95e74716f", ModuleType.Recording, 1)]
    public partial class 確認_宿泊プラン_一般会員 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_宿泊プラン_一般会員 instance = new 確認_宿泊プラン_一般会員();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_宿泊プラン_一般会員()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_宿泊プラン_一般会員 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_宿泊予約.label_ディナー付きプラン'.", repo.Hotelサイト.Hotel_宿泊予約.label_ディナー付きプランInfo, new RecordItemIndex(0));
                Validate.Exists(repo.Hotelサイト.Hotel_宿泊予約.label_ディナー付きプランInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_宿泊予約.label_お得なプラン'.", repo.Hotelサイト.Hotel_宿泊予約.label_お得なプランInfo, new RecordItemIndex(1));
                Validate.Exists(repo.Hotelサイト.Hotel_宿泊予約.label_お得なプランInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating NotExists on item 'Hotelサイト.Hotel_宿泊予約.label_プレミアムプラン'.", repo.Hotelサイト.Hotel_宿泊予約.label_プレミアムプランInfo, new RecordItemIndex(2));
                Validate.NotExists(repo.Hotelサイト.Hotel_宿泊予約.label_プレミアムプランInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
