///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.アイコン設定
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_アイコン選択 recording.
    /// </summary>
    [TestModule("ee4f20af-607c-421b-98d6-de7be75f3c9b", ModuleType.Recording, 1)]
    public partial class 操作_アイコン選択 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_アイコン選択 instance = new 操作_アイコン選択();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_アイコン選択()
        {
            folderpath = "";
            fullpath = "";
            filename = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_アイコン選択 Instance
        {
            get { return instance; }
        }

#region Variables

        string _folderpath;

        /// <summary>
        /// Gets or sets the value of variable folderpath.
        /// </summary>
        [TestVariable("a268ec50-3095-469d-a3ae-38da1d4e042f")]
        public string folderpath
        {
            get { return _folderpath; }
            set { _folderpath = value; }
        }

        string _fullpath;

        /// <summary>
        /// Gets or sets the value of variable fullpath.
        /// </summary>
        [TestVariable("72b6377b-1c99-42fa-a723-d3454bcc8115")]
        public string fullpath
        {
            get { return _fullpath; }
            set { _fullpath = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable filename.
        /// </summary>
        [TestVariable("a17411d9-a829-458a-8b68-79576ba0b5ff")]
        public string filename
        {
            get { return repo.fileName; }
            set { repo.fileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.Hotel_アイコン設定画面.button_ファイルを選択' at Center.", repo.Hotelサイト.Hotel_アイコン設定画面.button_ファイルを選択Info, new RecordItemIndex(0));
            repo.Hotelサイト.Hotel_アイコン設定画面.button_ファイルを選択.Click();
            Delay.Milliseconds(0);
            
            folderpath = UserCode.UserCodeCollection.GetDataFolderPath();
            Delay.Milliseconds(0);
            
            fullpath = UserCode.UserCodeCollection.PathCombine(folderpath, filename);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$fullpath' on item 'ダイアログ_ファイル選択_アイコン設定.textbox_ファイル名'.", repo.ダイアログ_ファイル選択_アイコン設定.textbox_ファイル名Info, new RecordItemIndex(3));
            repo.ダイアログ_ファイル選択_アイコン設定.textbox_ファイル名.Element.SetAttributeValue("Text", fullpath);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ダイアログ_ファイル選択_アイコン設定.button_開く' at Center.", repo.ダイアログ_ファイル選択_アイコン設定.button_開くInfo, new RecordItemIndex(4));
            repo.ダイアログ_ファイル選択_アイコン設定.button_開く.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to not exist. Associated repository item: 'ダイアログ_ファイル選択_アイコン設定'", repo.ダイアログ_ファイル選択_アイコン設定.SelfInfo, new ActionTimeout(10000), new RecordItemIndex(5));
            repo.ダイアログ_ファイル選択_アイコン設定.SelfInfo.WaitForNotExists(10000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
