///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.アイコン設定
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_アイコンサイズ変更 recording.
    /// </summary>
    [TestModule("b2dedcee-d3c9-4e45-9faf-57801467ab47", ModuleType.Recording, 1)]
    public partial class 操作_アイコンサイズ変更 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_アイコンサイズ変更 instance = new 操作_アイコンサイズ変更();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_アイコンサイズ変更()
        {
            zoom = "0;0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_アイコンサイズ変更 Instance
        {
            get { return instance; }
        }

#region Variables

        string _zoom;

        /// <summary>
        /// Gets or sets the value of variable zoom.
        /// </summary>
        [TestVariable("561f5f2c-77e2-4d31-88f6-c7a8eb52ae56")]
        public string zoom
        {
            get { return _zoom; }
            set { _zoom = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Hotelサイト.Hotel_アイコン設定画面.slider_拡大縮小' at Center.", repo.Hotelサイト.Hotel_アイコン設定画面.slider_拡大縮小Info, new RecordItemIndex(0));
            repo.Hotelサイト.Hotel_アイコン設定画面.slider_拡大縮小.MoveTo();
            repo.Hotelサイト.Hotel_アイコン設定画面.slider_拡大縮小.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Hotelサイト.Hotel_アイコン設定画面.slider_拡大縮小' at position from variable $zoom.", repo.Hotelサイト.Hotel_アイコン設定画面.slider_拡大縮小Info, new RecordItemIndex(1));
            repo.Hotelサイト.Hotel_アイコン設定画面.slider_拡大縮小.MoveTo(zoom);
            repo.Hotelサイト.Hotel_アイコン設定画面.slider_拡大縮小.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
