///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.アイコン設定
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_アイコン設定_エラーメッセージ recording.
    /// </summary>
    [TestModule("ff17be65-26a6-4f3f-8661-e683d186dd5f", ModuleType.Recording, 1)]
    public partial class 確認_アイコン設定_エラーメッセージ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_アイコン設定_エラーメッセージ instance = new 確認_アイコン設定_エラーメッセージ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_アイコン設定_エラーメッセージ()
        {
            icon_message = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_アイコン設定_エラーメッセージ Instance
        {
            get { return instance; }
        }

#region Variables

        string _icon_message;

        /// <summary>
        /// Gets or sets the value of variable icon_message.
        /// </summary>
        [TestVariable("04524c76-d0e7-4e41-bf9e-61172b67d7cf")]
        public string icon_message
        {
            get { return _icon_message; }
            set { _icon_message = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_アイコン設定画面'.", repo.Hotelサイト.Hotel_アイコン設定画面.SelfInfo, new RecordItemIndex(0));
                Validate.Exists(repo.Hotelサイト.Hotel_アイコン設定画面.SelfInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$icon_message) on item 'Hotelサイト.Hotel_アイコン設定画面.label_エラーメッセージ'.", repo.Hotelサイト.Hotel_アイコン設定画面.label_エラーメッセージInfo, new RecordItemIndex(1));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_アイコン設定画面.label_エラーメッセージInfo, "InnerText", icon_message, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
