///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.アイコン設定
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_プレビュー画像サイズ recording.
    /// </summary>
    [TestModule("99e1f1db-a91e-4088-ad0d-0c6e4ee2d02b", ModuleType.Recording, 1)]
    public partial class 確認_プレビュー画像サイズ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_プレビュー画像サイズ instance = new 確認_プレビュー画像サイズ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_プレビュー画像サイズ()
        {
            icon_img = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_プレビュー画像サイズ Instance
        {
            get { return instance; }
        }

#region Variables

        string _icon_img;

        /// <summary>
        /// Gets or sets the value of variable icon_img.
        /// </summary>
        [TestVariable("109fe6c5-37f9-4336-8b87-522cd2643290")]
        public string icon_img
        {
            get { return _icon_img; }
            set { _icon_img = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (style>$icon_img) on item 'Hotelサイト.Hotel_アイコン設定画面.img_プレビュー画像'.", repo.Hotelサイト.Hotel_アイコン設定画面.img_プレビュー画像Info, new RecordItemIndex(0));
                Validate.AttributeContains(repo.Hotelサイト.Hotel_アイコン設定画面.img_プレビュー画像Info, "style", icon_img, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
