///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約確認
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_宿泊予約情報 recording.
    /// </summary>
    [TestModule("8d5eb14e-f70a-4e9c-94f4-cea5a0357b6e", ModuleType.Recording, 1)]
    public partial class 確認_宿泊予約情報 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_宿泊予約情報 instance = new 確認_宿泊予約情報();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_宿泊予約情報()
        {
            planName = "";
            total_bill = "";
            checkcontact = "";
            checkterm = "";
            plan_desc = "";
            checkcomment = "";
            check_head_count = "";
            beforedate = "";
            afterdate = "";
            checkUserName = "";
            checkDate = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_宿泊予約情報 Instance
        {
            get { return instance; }
        }

#region Variables

        string _total_bill;

        /// <summary>
        /// Gets or sets the value of variable total_bill.
        /// </summary>
        [TestVariable("dbafd20e-b64a-46eb-98da-a312f867626b")]
        public string total_bill
        {
            get { return _total_bill; }
            set { _total_bill = value; }
        }

        string _checkcontact;

        /// <summary>
        /// Gets or sets the value of variable checkcontact.
        /// </summary>
        [TestVariable("6efcb1e9-00c9-4846-8c42-ed55fc553f8f")]
        public string checkcontact
        {
            get { return _checkcontact; }
            set { _checkcontact = value; }
        }

        string _checkterm;

        /// <summary>
        /// Gets or sets the value of variable checkterm.
        /// </summary>
        [TestVariable("852b00db-5235-4942-9f6b-6ed83f2a11cc")]
        public string checkterm
        {
            get { return _checkterm; }
            set { _checkterm = value; }
        }

        string _plan_desc;

        /// <summary>
        /// Gets or sets the value of variable plan_desc.
        /// </summary>
        [TestVariable("4aa421b1-0d7d-4bc3-a319-f6882f44c623")]
        public string plan_desc
        {
            get { return _plan_desc; }
            set { _plan_desc = value; }
        }

        string _checkcomment;

        /// <summary>
        /// Gets or sets the value of variable checkcomment.
        /// </summary>
        [TestVariable("af748012-a58a-49a2-b557-973549e1ece6")]
        public string checkcomment
        {
            get { return _checkcomment; }
            set { _checkcomment = value; }
        }

        string _check_head_count;

        /// <summary>
        /// Gets or sets the value of variable check_head_count.
        /// </summary>
        [TestVariable("ac3e966f-616e-4e3f-ba11-9365dd460b84")]
        public string check_head_count
        {
            get { return _check_head_count; }
            set { _check_head_count = value; }
        }

        string _beforedate;

        /// <summary>
        /// Gets or sets the value of variable beforedate.
        /// </summary>
        [TestVariable("def7ed32-e254-4f42-97dc-8183951b5746")]
        public string beforedate
        {
            get { return _beforedate; }
            set { _beforedate = value; }
        }

        string _afterdate;

        /// <summary>
        /// Gets or sets the value of variable afterdate.
        /// </summary>
        [TestVariable("1a207b67-22dc-49b5-a766-b8abdb845429")]
        public string afterdate
        {
            get { return _afterdate; }
            set { _afterdate = value; }
        }

        string _checkUserName;

        /// <summary>
        /// Gets or sets the value of variable checkUserName.
        /// </summary>
        [TestVariable("d15b4f00-fa7f-4562-9f0c-1bbd7259b4a2")]
        public string checkUserName
        {
            get { return _checkUserName; }
            set { _checkUserName = value; }
        }

        string _checkDate;

        /// <summary>
        /// Gets or sets the value of variable checkDate.
        /// </summary>
        [TestVariable("0742b75e-7e31-402a-bf75-d8a82933f5b3")]
        public string checkDate
        {
            get { return _checkDate; }
            set { _checkDate = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable planName.
        /// </summary>
        [TestVariable("cb66af3c-eae2-4b6e-b32c-168e1491f81b")]
        public string planName
        {
            get { return repo.planName; }
            set { repo.planName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_宿泊予約確認画面'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.SelfInfo, new RecordItemIndex(0));
                Validate.Exists(repo.Hotelサイト.Hotel_宿泊予約確認画面.SelfInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (InnerText>$total_bill) on item 'Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_合計金額'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_合計金額Info, new RecordItemIndex(1));
                Validate.AttributeContains(repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_合計金額Info, "InnerText", total_bill, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$planName) on item 'Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_プラン名'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_プラン名Info, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_プラン名Info, "InnerText", planName, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$plan_desc) on item 'Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_プラン詳細'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_プラン詳細Info, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_プラン詳細Info, "InnerText", plan_desc, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$checkDate) on item 'Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_宿泊日'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_宿泊日Info, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_宿泊日Info, "InnerText", checkDate, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$check_head_count) on item 'Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_人数'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_人数Info, new RecordItemIndex(5));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_人数Info, "InnerText", check_head_count, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$checkUserName) on item 'Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_お名前'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_お名前Info, new RecordItemIndex(6));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_お名前Info, "InnerText", checkUserName, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (InnerText>$checkcontact) on item 'Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_確認のご連絡'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_確認のご連絡Info, new RecordItemIndex(7));
                Validate.AttributeContains(repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_確認のご連絡Info, "InnerText", checkcontact, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (InnerText>$checkcomment) on item 'Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_ご要望'.", repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_ご要望Info, new RecordItemIndex(8));
                Validate.AttributeContains(repo.Hotelサイト.Hotel_宿泊予約確認画面.予約情報.label_ご要望Info, "InnerText", checkcomment, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
