///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Usercode.画像比較
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_ログアウトボタン recording.
    /// </summary>
    [TestModule("f7474525-d186-43c0-ae91-619715c5bd54", ModuleType.Recording, 1)]
    public partial class 確認_ログアウトボタン : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_ログアウトボタン instance = new 確認_ログアウトボタン();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_ログアウトボタン()
        {
            evidenceFileName = "";
            evidenceFolderPath = "";
            targetName = "";
            fileExtension = "";
            resultFileName = "";
            resultFolderPath = "";
            targetFolderPath = "";
            targetFileName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_ログアウトボタン Instance
        {
            get { return instance; }
        }

#region Variables

        string _evidenceFileName;

        /// <summary>
        /// Gets or sets the value of variable evidenceFileName.
        /// </summary>
        [TestVariable("83cd4978-03f4-4d6a-8de5-89d00f3e6493")]
        public string evidenceFileName
        {
            get { return _evidenceFileName; }
            set { _evidenceFileName = value; }
        }

        string _evidenceFolderPath;

        /// <summary>
        /// Gets or sets the value of variable evidenceFolderPath.
        /// </summary>
        [TestVariable("b49de56a-d5a2-43c2-b654-72587522d453")]
        public string evidenceFolderPath
        {
            get { return _evidenceFolderPath; }
            set { _evidenceFolderPath = value; }
        }

        string _targetName;

        /// <summary>
        /// Gets or sets the value of variable targetName.
        /// </summary>
        [TestVariable("7dd6da7e-18c7-4161-b30c-73c37c1665eb")]
        public string targetName
        {
            get { return _targetName; }
            set { _targetName = value; }
        }

        string _fileExtension;

        /// <summary>
        /// Gets or sets the value of variable fileExtension.
        /// </summary>
        [TestVariable("9f378121-2883-41b8-9c69-9a440016f5ce")]
        public string fileExtension
        {
            get { return _fileExtension; }
            set { _fileExtension = value; }
        }

        string _resultFileName;

        /// <summary>
        /// Gets or sets the value of variable resultFileName.
        /// </summary>
        [TestVariable("200899e5-9986-43cb-be7c-457b7a23bb43")]
        public string resultFileName
        {
            get { return _resultFileName; }
            set { _resultFileName = value; }
        }

        string _resultFolderPath;

        /// <summary>
        /// Gets or sets the value of variable resultFolderPath.
        /// </summary>
        [TestVariable("3e3d7b5b-f794-419c-b1ac-4b4cb0358b44")]
        public string resultFolderPath
        {
            get { return _resultFolderPath; }
            set { _resultFolderPath = value; }
        }

        string _targetFolderPath;

        /// <summary>
        /// Gets or sets the value of variable targetFolderPath.
        /// </summary>
        [TestVariable("999abd7a-25f7-42da-81ce-4664ab8a7788")]
        public string targetFolderPath
        {
            get { return _targetFolderPath; }
            set { _targetFolderPath = value; }
        }

        string _targetFileName;

        /// <summary>
        /// Gets or sets the value of variable targetFileName.
        /// </summary>
        [TestVariable("35fef72d-9857-4254-a4fa-5311e5f46420")]
        public string targetFileName
        {
            get { return _targetFileName; }
            set { _targetFileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // ログアウトボタンの画像比較をエビデンスフォルダ作成で作成したフォルダパスを使用する
            Report.Log(ReportLevel.Info, "Section", "ログアウトボタンの画像比較をエビデンスフォルダ作成で作成したフォルダパスを使用する", new RecordItemIndex(0));
            
            evidenceFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(evidenceFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            resultFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(resultFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            targetFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(targetFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Hotelサイト.Hotel_共通.共通動作.button_ログアウト' at Center.", repo.Hotelサイト.Hotel_共通.共通動作.button_ログアウトInfo, new RecordItemIndex(4));
            repo.Hotelサイト.Hotel_共通.共通動作.button_ログアウト.MoveTo();
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection_ImageCompare.GetScreenshot(repo.Hotelサイト.Hotel_共通.bodyInfo, evidenceFileName);
            Delay.Milliseconds(0);
            
            try {
                UserCode.UserCodeCollection_ImageCompare.ValidateCompareImageBitmap(evidenceFileName, targetFileName, resultFileName);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
