///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Usercode.画像比較
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_ログイン画面 recording.
    /// </summary>
    [TestModule("76659325-82e1-4805-b906-077c30110e96", ModuleType.Recording, 1)]
    public partial class 確認_ログイン画面 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_ログイン画面 instance = new 確認_ログイン画面();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_ログイン画面()
        {
            evidenceFileName = "";
            evidenceFolderPath = "";
            targetName = "";
            fileExtension = "";
            resultFileName = "";
            resultFolderPath = "";
            targetFileName = "";
            targetFolderPath = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_ログイン画面 Instance
        {
            get { return instance; }
        }

#region Variables

        string _evidenceFileName;

        /// <summary>
        /// Gets or sets the value of variable evidenceFileName.
        /// </summary>
        [TestVariable("1edc8e58-956b-4c05-89fb-c956ce62f620")]
        public string evidenceFileName
        {
            get { return _evidenceFileName; }
            set { _evidenceFileName = value; }
        }

        string _evidenceFolderPath;

        /// <summary>
        /// Gets or sets the value of variable evidenceFolderPath.
        /// </summary>
        [TestVariable("609ec8c2-a325-4191-b979-8228bdbdf746")]
        public string evidenceFolderPath
        {
            get { return _evidenceFolderPath; }
            set { _evidenceFolderPath = value; }
        }

        string _targetName;

        /// <summary>
        /// Gets or sets the value of variable targetName.
        /// </summary>
        [TestVariable("9b48a62d-4a05-4718-818f-e70e239891e4")]
        public string targetName
        {
            get { return _targetName; }
            set { _targetName = value; }
        }

        string _fileExtension;

        /// <summary>
        /// Gets or sets the value of variable fileExtension.
        /// </summary>
        [TestVariable("792bf607-27e1-49c1-addc-d38ba37c88a6")]
        public string fileExtension
        {
            get { return _fileExtension; }
            set { _fileExtension = value; }
        }

        string _resultFileName;

        /// <summary>
        /// Gets or sets the value of variable resultFileName.
        /// </summary>
        [TestVariable("2c6dcec9-34c5-4c03-bccb-e43eb33c2acc")]
        public string resultFileName
        {
            get { return _resultFileName; }
            set { _resultFileName = value; }
        }

        string _resultFolderPath;

        /// <summary>
        /// Gets or sets the value of variable resultFolderPath.
        /// </summary>
        [TestVariable("b4df50c0-a5a8-42a0-b5b1-9aa5522ab18a")]
        public string resultFolderPath
        {
            get { return _resultFolderPath; }
            set { _resultFolderPath = value; }
        }

        string _targetFileName;

        /// <summary>
        /// Gets or sets the value of variable targetFileName.
        /// </summary>
        [TestVariable("c68f484a-bdc9-4305-b987-55b6da814410")]
        public string targetFileName
        {
            get { return _targetFileName; }
            set { _targetFileName = value; }
        }

        string _targetFolderPath;

        /// <summary>
        /// Gets or sets the value of variable targetFolderPath.
        /// </summary>
        [TestVariable("f6252c40-79ee-46ae-ad6d-2ac8ea7b4b63")]
        public string targetFolderPath
        {
            get { return _targetFolderPath; }
            set { _targetFolderPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // ログイン画面の（画面下部を除いての）画像比較をエビデンスフォルダ作成で作成したフォルダパスを使用する
            Report.Log(ReportLevel.Info, "Section", "ログイン画面の（画面下部を除いての）画像比較をエビデンスフォルダ作成で作成したフォルダパスを使用する", new RecordItemIndex(0));
            
            UserCode.UserCodeCollection_ImageCompare.InitializationIgnoreRectangles();
            Delay.Milliseconds(0);
            
            evidenceFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(evidenceFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            resultFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(resultFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            targetFileName = UserCode.UserCodeCollection_ImageCompare.GetCombinePathExtension(targetFolderPath, targetName, "", fileExtension);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection_ImageCompare.GetScreenshot(repo.Hotelサイト.Hotel_ログイン画面.bodyInfo, evidenceFileName);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection_ImageCompare.AddIgnoreRectUnknown(repo.Hotelサイト.Hotel_ログイン画面.フッターInfo, repo.Hotelサイト.Hotel_ログイン画面.bodyInfo);
            Delay.Milliseconds(0);
            
            try {
                UserCode.UserCodeCollection_ImageCompare.ValidateCompareImageBitmapIgnore(evidenceFileName, targetFileName, resultFileName);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
