///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Demoアプリ.共通
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_UI_elementタブ開く recording.
    /// </summary>
    [TestModule("13667a4d-347a-416b-9710-f92a756795ff", ModuleType.Recording, 1)]
    public partial class 操作_UI_elementタブ開く : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.DemoApp repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.DemoApp repo = global::HotelTrainingTest.Repository.DemoApp.Instance;

        static 操作_UI_elementタブ開く instance = new 操作_UI_elementタブ開く();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_UI_elementタブ開く()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_UI_elementタブ開く Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxDemoApp.タブ関連.tab_UI_element_test_area' at Center.", repo.RxDemoApp.タブ関連.tab_UI_element_test_areaInfo, new RecordItemIndex(0));
            repo.RxDemoApp.タブ関連.tab_UI_element_test_area.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'RxDemoApp.タブ関連.UI_elementタブ'", repo.RxDemoApp.タブ関連.UI_elementタブ.SelfInfo, new ActionTimeout(5000), new RecordItemIndex(1));
            repo.RxDemoApp.タブ関連.UI_elementタブ.SelfInfo.WaitForExists(5000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
