///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Usercode
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The T2_8_2_会員登録おためし recording.
    /// </summary>
    [TestModule("ccc365f4-9bf9-4d3c-9bcd-1a1082f4d8b2", ModuleType.Recording, 1)]
    public partial class T2_8_2_会員登録おためし : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static T2_8_2_会員登録おためし instance = new T2_8_2_会員登録おためし();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public T2_8_2_会員登録おためし()
        {
            email = "";
            password = "";
            password_com = "";
            username = "";
            rank = "";
            address = "札幌市";
            tel = "";
            gender = "";
            birthday = "";
            notification = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static T2_8_2_会員登録おためし Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("a8998c14-4a3f-4f07-9a76-120ea5f215d7")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("e8f325c4-5160-4b2c-88bd-2bfe7063866a")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

        string _password_com;

        /// <summary>
        /// Gets or sets the value of variable password_com.
        /// </summary>
        [TestVariable("35d8c904-8d71-42b1-b215-c43c86dbec93")]
        public string password_com
        {
            get { return _password_com; }
            set { _password_com = value; }
        }

        string _address;

        /// <summary>
        /// Gets or sets the value of variable address.
        /// </summary>
        [TestVariable("c75e74f8-18f7-45c8-a1ed-6bd8d9fae8d2")]
        public string address
        {
            get { return _address; }
            set { _address = value; }
        }

        string _tel;

        /// <summary>
        /// Gets or sets the value of variable tel.
        /// </summary>
        [TestVariable("1adc24da-9d54-4e19-ac16-314a081ef438")]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        string _gender;

        /// <summary>
        /// Gets or sets the value of variable gender.
        /// </summary>
        [TestVariable("44a98f91-815a-4f5e-8fb9-e52f053a1c51")]
        public string gender
        {
            get { return _gender; }
            set { _gender = value; }
        }

        string _birthday;

        /// <summary>
        /// Gets or sets the value of variable birthday.
        /// </summary>
        [TestVariable("4b7a59d2-441b-457a-a5d2-e6228565e3c0")]
        public string birthday
        {
            get { return _birthday; }
            set { _birthday = value; }
        }

        string _notification;

        /// <summary>
        /// Gets or sets the value of variable notification.
        /// </summary>
        [TestVariable("a865744a-8421-48d4-95fd-bd9b477d4d41")]
        public string notification
        {
            get { return _notification; }
            set { _notification = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable rank.
        /// </summary>
        [TestVariable("5c0ee3d3-01f4-499e-adfb-1e45d8d74ebe")]
        public string rank
        {
            get { return repo.rank; }
            set { repo.rank = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("52d0504e-4c1c-471f-858c-c79235ccfca9")]
        public string username
        {
            get { return repo.username; }
            set { repo.username = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_メールアドレスInfo, email);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_パスワードInfo, password);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_確認用パスワードInfo, password_com);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_氏名Info, username);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.radio_会員ランクInfo, rank);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_住所Info, address);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_電話番号Info, tel);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.select_性別Info, gender);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_誕生日Info, birthday);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.chcekbox_お知らせを受け取るInfo, notification);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
