///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Usercode
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UserCode練習1 recording.
    /// </summary>
    [TestModule("0542dd0a-ad2b-44f5-a81d-0429939de945", ModuleType.Recording, 1)]
    public partial class UserCode練習1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static UserCode練習1 instance = new UserCode練習1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UserCode練習1()
        {
            num = "";
            str = "";
            today = "";
            date1 = "";
            dateControl = "";
            date2 = "";
            dateConcatemation = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UserCode練習1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _num;

        /// <summary>
        /// Gets or sets the value of variable num.
        /// </summary>
        [TestVariable("28713f99-750f-4f18-a0d6-56fcee08c859")]
        public string num
        {
            get { return _num; }
            set { _num = value; }
        }

        string _str;

        /// <summary>
        /// Gets or sets the value of variable str.
        /// </summary>
        [TestVariable("b42c18c2-f37e-47fd-a850-d7187270ff9a")]
        public string str
        {
            get { return _str; }
            set { _str = value; }
        }

        string _today;

        /// <summary>
        /// Gets or sets the value of variable today.
        /// </summary>
        [TestVariable("fd4da7cb-b156-4ceb-b5e3-2eacdde350a6")]
        public string today
        {
            get { return _today; }
            set { _today = value; }
        }

        string _date1;

        /// <summary>
        /// Gets or sets the value of variable date1.
        /// </summary>
        [TestVariable("5b04c80b-6cca-4ec4-8353-c0e2c99221f4")]
        public string date1
        {
            get { return _date1; }
            set { _date1 = value; }
        }

        string _dateControl;

        /// <summary>
        /// Gets or sets the value of variable dateControl.
        /// </summary>
        [TestVariable("10606742-9205-48de-9cb0-dd7f52e81cb9")]
        public string dateControl
        {
            get { return _dateControl; }
            set { _dateControl = value; }
        }

        string _date2;

        /// <summary>
        /// Gets or sets the value of variable date2.
        /// </summary>
        [TestVariable("694113cd-8a9d-46b1-978b-0fecd156046c")]
        public string date2
        {
            get { return _date2; }
            set { _date2 = value; }
        }

        string _dateConcatemation;

        /// <summary>
        /// Gets or sets the value of variable dateConcatemation.
        /// </summary>
        [TestVariable("f12b6b8e-9e74-47c8-8a3a-af2c9b37a794")]
        public string dateConcatemation
        {
            get { return _dateConcatemation; }
            set { _dateConcatemation = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // 練習1-1 文字列結合
            Report.Log(ReportLevel.Info, "Section", "練習1-1 文字列結合", new RecordItemIndex(0));
            
            str = UserCode.UserCodeCollection.ConcatenationStr("hoge", "fuga");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", str, new RecordItemIndex(2));
            
            // 練習1-2 今日の日付を取得
            Report.Log(ReportLevel.Info, "Section", "練習1-2 今日の日付を取得", new RecordItemIndex(3));
            
            today = UserCode.UserCodeCollection.GetToday();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", today, new RecordItemIndex(5));
            
            // 練習1-3 日付のコントロール
            Report.Log(ReportLevel.Info, "Section", "練習1-3 日付のコントロール", new RecordItemIndex(6));
            
            dateControl = UserCode.UserCodeCollection.DateControl();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", dateControl, new RecordItemIndex(8));
            
            // 練習1-4 日付実践
            Report.Log(ReportLevel.Info, "Section", "練習1-4 日付実践", new RecordItemIndex(9));
            
            dateConcatemation = UserCode.UserCodeCollection.DateConcatenation(date1, date2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", dateConcatemation, new RecordItemIndex(11));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
