///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module_Usercode
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_予約情報入力_UserCode recording.
    /// </summary>
    [TestModule("c923d4ab-3c68-48f3-83fc-d206548a4ac3", ModuleType.Recording, 1)]
    public partial class 操作_予約情報入力_UserCode : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_予約情報入力_UserCode instance = new 操作_予約情報入力_UserCode();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_予約情報入力_UserCode()
        {
            date = "";
            term = "";
            head_count = "";
            breakfast = "";
            early_check_in = "";
            sightseeing = "";
            username = "";
            contact = "";
            email = "";
            tel = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_予約情報入力_UserCode Instance
        {
            get { return instance; }
        }

#region Variables

        string _date;

        /// <summary>
        /// Gets or sets the value of variable date.
        /// </summary>
        [TestVariable("d95dc177-5cb0-4327-9f21-71b7c185a767")]
        public string date
        {
            get { return _date; }
            set { _date = value; }
        }

        string _term;

        /// <summary>
        /// Gets or sets the value of variable term.
        /// </summary>
        [TestVariable("f33bd0dc-90b8-4cd5-b840-7b259e03ca6d")]
        public string term
        {
            get { return _term; }
            set { _term = value; }
        }

        string _head_count;

        /// <summary>
        /// Gets or sets the value of variable head_count.
        /// </summary>
        [TestVariable("ee4dbf7e-a981-4e24-9464-38b5f564e8ef")]
        public string head_count
        {
            get { return _head_count; }
            set { _head_count = value; }
        }

        string _breakfast;

        /// <summary>
        /// Gets or sets the value of variable breakfast.
        /// </summary>
        [TestVariable("0174fd56-c647-46cc-92ea-33a5b5775918")]
        public string breakfast
        {
            get { return _breakfast; }
            set { _breakfast = value; }
        }

        string _early_check_in;

        /// <summary>
        /// Gets or sets the value of variable early_check_in.
        /// </summary>
        [TestVariable("92b876db-4369-44fe-a68a-62be0465e920")]
        public string early_check_in
        {
            get { return _early_check_in; }
            set { _early_check_in = value; }
        }

        string _sightseeing;

        /// <summary>
        /// Gets or sets the value of variable sightseeing.
        /// </summary>
        [TestVariable("2e283bb4-e3fd-449f-8e42-4919d3b965e3")]
        public string sightseeing
        {
            get { return _sightseeing; }
            set { _sightseeing = value; }
        }

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("78e77536-f198-4702-b410-8249718062ce")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _tel;

        /// <summary>
        /// Gets or sets the value of variable tel.
        /// </summary>
        [TestVariable("00fe48bc-44a3-4bda-9b1a-c96aca2f2e25")]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("7e2d6cb8-c7c5-4f4f-86ad-9cb7e903eba8")]
        public string username
        {
            get { return repo.username; }
            set { repo.username = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable contact.
        /// </summary>
        [TestVariable("8c2367a8-7566-4383-a5f4-d686f9180900")]
        public string contact
        {
            get { return repo.contact; }
            set { repo.contact = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_宿泊日Info, date);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_宿泊数Info, term);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_人数Info, head_count);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.checkbox_朝食バイキングInfo, breakfast);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.checkbox_昼からチェックインプランInfo, early_check_in);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.checkbox_お得な観光プランInfo, sightseeing);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名Info, username);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.select_確認のご連絡Info, contact);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_メールアドレスInfo, email);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_電話番号Info, tel);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
