///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.会員登録
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_会員登録 recording.
    /// </summary>
    [TestModule("2eb1484c-f0df-41bc-acca-4aa1d5a89c54", ModuleType.Recording, 1)]
    public partial class 操作_会員登録 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_会員登録 instance = new 操作_会員登録();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_会員登録()
        {
            email = "";
            password = "(null)";
            password_confirmation = "";
            username = "";
            rank = "";
            address = "";
            tel = "";
            gender = "";
            birthday = "";
            notification = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_会員登録 Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("d73a4936-183e-446d-83a4-783f39705969")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("f016185a-cc8d-4dae-9df1-d054206b8a47")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

        string _password_confirmation;

        /// <summary>
        /// Gets or sets the value of variable password_confirmation.
        /// </summary>
        [TestVariable("735427bc-9d54-4e46-91d9-56eeacc21237")]
        public string password_confirmation
        {
            get { return _password_confirmation; }
            set { _password_confirmation = value; }
        }

        string _address;

        /// <summary>
        /// Gets or sets the value of variable address.
        /// </summary>
        [TestVariable("f6b91790-8514-4c1e-b896-fed20776cb56")]
        public string address
        {
            get { return _address; }
            set { _address = value; }
        }

        string _tel;

        /// <summary>
        /// Gets or sets the value of variable tel.
        /// </summary>
        [TestVariable("f932389c-cc8d-4c10-b2e1-2ac508e00377")]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        string _gender;

        /// <summary>
        /// Gets or sets the value of variable gender.
        /// </summary>
        [TestVariable("975f5c7a-8d29-4aa0-9088-17c28cca6a9d")]
        public string gender
        {
            get { return _gender; }
            set { _gender = value; }
        }

        string _birthday;

        /// <summary>
        /// Gets or sets the value of variable birthday.
        /// </summary>
        [TestVariable("df87a3ae-d0b3-445c-ad4a-ad98455e4f04")]
        public string birthday
        {
            get { return _birthday; }
            set { _birthday = value; }
        }

        string _notification;

        /// <summary>
        /// Gets or sets the value of variable notification.
        /// </summary>
        [TestVariable("c687da77-d6c1-49a5-8212-68342f6a6c8a")]
        public string notification
        {
            get { return _notification; }
            set { _notification = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable rank.
        /// </summary>
        [TestVariable("912c7e91-70ac-410e-803f-3b9d8ecdb1d9")]
        public string rank
        {
            get { return repo.rank; }
            set { repo.rank = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("b6ec3ba9-4290-443d-b18e-b000aa2bb532")]
        public string username
        {
            get { return repo.username; }
            set { repo.username = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.Hotel_共通.共通動作.link_会員登録' at Center.", repo.Hotelサイト.Hotel_共通.共通動作.link_会員登録Info, new RecordItemIndex(0));
            repo.Hotelサイト.Hotel_共通.共通動作.link_会員登録.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded('5000ms') on item 'Hotelサイト.Hotel_共通'.", repo.Hotelサイト.Hotel_共通.SelfInfo, new RecordItemIndex(1));
            repo.Hotelサイト.Hotel_共通.Self.WaitForDocumentLoaded(ValueConverter.ArgumentFromString<Ranorex.Duration>("timeout", "5000ms"));
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_メールアドレスInfo, email);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_パスワードInfo, password);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_確認用パスワードInfo, password_confirmation);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_氏名Info, username);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.radio_会員ランクInfo, rank);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_住所Info, address);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_電話番号Info, tel);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.select_性別Info, gender);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_誕生日Info, birthday);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.chcekbox_お知らせを受け取るInfo, notification);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.Hotel_会員登録.button_登録' at Center.", repo.Hotelサイト.Hotel_会員登録.button_登録Info, new RecordItemIndex(12));
            repo.Hotelサイト.Hotel_会員登録.button_登録.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded('5000ms') on item 'Hotelサイト.Hotel_共通'.", repo.Hotelサイト.Hotel_共通.SelfInfo, new RecordItemIndex(13));
            repo.Hotelサイト.Hotel_共通.Self.WaitForDocumentLoaded(ValueConverter.ArgumentFromString<Ranorex.Duration>("timeout", "5000ms"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
