///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.会員登録
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_会員登録情報入力_エラー確認用 recording.
    /// </summary>
    [TestModule("c637ae92-d20e-4389-bfeb-d9ed00a8cebe", ModuleType.Recording, 1)]
    public partial class 操作_会員登録情報入力_エラー確認用 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_会員登録情報入力_エラー確認用 instance = new 操作_会員登録情報入力_エラー確認用();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_会員登録情報入力_エラー確認用()
        {
            email = "";
            password = "";
            password_confirmation = "";
            username = "";
            rank = "";
            address = "";
            tel = "";
            gender = "";
            birthday = "";
            notification = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_会員登録情報入力_エラー確認用 Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("544aa92d-e27f-47cc-b46f-3e654f426aa7")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("ace01f51-2701-45c8-86d2-f00478d7964a")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

        string _password_confirmation;

        /// <summary>
        /// Gets or sets the value of variable password_confirmation.
        /// </summary>
        [TestVariable("3a2e237a-3ec6-4198-bd5e-807c943c9e2e")]
        public string password_confirmation
        {
            get { return _password_confirmation; }
            set { _password_confirmation = value; }
        }

        string _address;

        /// <summary>
        /// Gets or sets the value of variable address.
        /// </summary>
        [TestVariable("3ad7aa52-e4a1-463e-9d0e-af4b7300b620")]
        public string address
        {
            get { return _address; }
            set { _address = value; }
        }

        string _tel;

        /// <summary>
        /// Gets or sets the value of variable tel.
        /// </summary>
        [TestVariable("43ba1ab8-4035-4f2c-9621-23ad695ae148")]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        string _gender;

        /// <summary>
        /// Gets or sets the value of variable gender.
        /// </summary>
        [TestVariable("37e18b8a-5156-4205-9ebc-62d028a1aa8b")]
        public string gender
        {
            get { return _gender; }
            set { _gender = value; }
        }

        string _birthday;

        /// <summary>
        /// Gets or sets the value of variable birthday.
        /// </summary>
        [TestVariable("4a57833f-10b6-4af2-84fc-e4bbf61bc475")]
        public string birthday
        {
            get { return _birthday; }
            set { _birthday = value; }
        }

        string _notification;

        /// <summary>
        /// Gets or sets the value of variable notification.
        /// </summary>
        [TestVariable("42b30b26-ff61-4d12-81f4-a8d8c7d77168")]
        public string notification
        {
            get { return _notification; }
            set { _notification = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable rank.
        /// </summary>
        [TestVariable("8eb54fbf-d5fe-4784-ab7d-2617bafaa2af")]
        public string rank
        {
            get { return repo.rank; }
            set { repo.rank = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("80d83479-6722-4ab1-937d-0aa96365ac6e")]
        public string username
        {
            get { return repo.username; }
            set { repo.username = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_メールアドレスInfo, email);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$password' with focus on 'Hotelサイト.Hotel_会員登録.情報入力.textbox_パスワード'.", repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_パスワードInfo, new RecordItemIndex(1));
            repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_パスワード.PressKeys(password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$password_confirmation' with focus on 'Hotelサイト.Hotel_会員登録.情報入力.textbox_確認用パスワード'.", repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_確認用パスワードInfo, new RecordItemIndex(2));
            repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_確認用パスワード.PressKeys(password_confirmation);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_氏名Info, username);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.radio_会員ランクInfo, rank);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_住所Info, address);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_電話番号Info, tel);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.select_性別Info, gender);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$birthday' with focus on 'Hotelサイト.Hotel_会員登録.情報入力.textbox_誕生日'.", repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_誕生日Info, new RecordItemIndex(8));
            repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_誕生日.PressKeys(birthday);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.chcekbox_お知らせを受け取るInfo, notification);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
