///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.会員登録
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_会員登録情報_入力 recording.
    /// </summary>
    [TestModule("85262a49-563b-42e9-a693-fd4cb5c81001", ModuleType.Recording, 1)]
    public partial class 操作_会員登録情報_入力 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_会員登録情報_入力 instance = new 操作_会員登録情報_入力();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_会員登録情報_入力()
        {
            email = "";
            password = "(null)";
            password_confirmation = "";
            username = "";
            rank = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_会員登録情報_入力 Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("e4de19a4-26c2-4a97-b927-6a13bfeda407")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("0f7f026a-255a-4e8e-be11-8b9d31182cfa")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

        string _password_confirmation;

        /// <summary>
        /// Gets or sets the value of variable password_confirmation.
        /// </summary>
        [TestVariable("1c2f8ecd-e507-4073-b54d-1eb56b07663e")]
        public string password_confirmation
        {
            get { return _password_confirmation; }
            set { _password_confirmation = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable rank.
        /// </summary>
        [TestVariable("5c0ee3d3-01f4-499e-adfb-1e45d8d74ebe")]
        public string rank
        {
            get { return repo.rank; }
            set { repo.rank = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("ce1ffda3-edc7-4955-a1ae-80a1a68ee9d9")]
        public string username
        {
            get { return repo.username; }
            set { repo.username = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_メールアドレスInfo, email);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_パスワードInfo, password);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_確認用パスワードInfo, password_confirmation);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_氏名Info, username);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.radio_会員ランクInfo, rank);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
