///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.会員登録
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_会員登録情報_全て入力 recording.
    /// </summary>
    [TestModule("c8bbff7c-99c5-4427-8f3f-88305722dd66", ModuleType.Recording, 1)]
    public partial class 操作_会員登録情報_全て入力 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_会員登録情報_全て入力 instance = new 操作_会員登録情報_全て入力();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_会員登録情報_全て入力()
        {
            rank = "";
            email = "";
            password = "";
            password_confirmation = "";
            username = "";
            address = "";
            tel = "";
            gender = "";
            birthday = "";
            notification = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_会員登録情報_全て入力 Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("dd96d713-6bfa-4885-929c-65cc68c77921")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("1b652051-29f3-4e62-938f-ecb70152486b")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

        string _password_confirmation;

        /// <summary>
        /// Gets or sets the value of variable password_confirmation.
        /// </summary>
        [TestVariable("93724f4b-83ba-40cd-a337-6ec67fba999e")]
        public string password_confirmation
        {
            get { return _password_confirmation; }
            set { _password_confirmation = value; }
        }

        string _address;

        /// <summary>
        /// Gets or sets the value of variable address.
        /// </summary>
        [TestVariable("917a7f44-348b-41f3-9e8c-36f01fbaab68")]
        public string address
        {
            get { return _address; }
            set { _address = value; }
        }

        string _tel;

        /// <summary>
        /// Gets or sets the value of variable tel.
        /// </summary>
        [TestVariable("ef2a8b19-64d4-4e28-9ab2-80eea4670461")]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        string _gender;

        /// <summary>
        /// Gets or sets the value of variable gender.
        /// </summary>
        [TestVariable("c02d9bbb-18e8-4264-b9d1-3c6e74658ba7")]
        public string gender
        {
            get { return _gender; }
            set { _gender = value; }
        }

        string _birthday;

        /// <summary>
        /// Gets or sets the value of variable birthday.
        /// </summary>
        [TestVariable("15be3454-6266-4156-8ce0-bacce12bf399")]
        public string birthday
        {
            get { return _birthday; }
            set { _birthday = value; }
        }

        string _notification;

        /// <summary>
        /// Gets or sets the value of variable notification.
        /// </summary>
        [TestVariable("76facaf7-ea7f-4315-b89b-fdfcdd02b6b9")]
        public string notification
        {
            get { return _notification; }
            set { _notification = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable rank.
        /// </summary>
        [TestVariable("5c0ee3d3-01f4-499e-adfb-1e45d8d74ebe")]
        public string rank
        {
            get { return repo.rank; }
            set { repo.rank = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("e58736de-0d17-430b-ac51-ac7adb1a1df0")]
        public string username
        {
            get { return repo.username; }
            set { repo.username = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_メールアドレスInfo, email);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_パスワードInfo, password);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_確認用パスワードInfo, password_confirmation);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_氏名Info, username);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.radio_会員ランクInfo, rank);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_住所Info, address);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_電話番号Info, tel);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.select_性別Info, gender);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.textbox_誕生日Info, birthday);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_会員登録.情報入力.chcekbox_お知らせを受け取るInfo, notification);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
