///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.会員登録
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_会員登録_エラーメッセージ recording.
    /// </summary>
    [TestModule("25c02fa1-bc38-4fb3-a69a-3aebbf13f2d9", ModuleType.Recording, 1)]
    public partial class 確認_会員登録_エラーメッセージ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_会員登録_エラーメッセージ instance = new 確認_会員登録_エラーメッセージ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_会員登録_エラーメッセージ()
        {
            email_message = "";
            password_message = "";
            password_confirm_message = "";
            username_message = "";
            tel_message = "";
            birthday_message = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_会員登録_エラーメッセージ Instance
        {
            get { return instance; }
        }

#region Variables

        string _email_message;

        /// <summary>
        /// Gets or sets the value of variable email_message.
        /// </summary>
        [TestVariable("232647fa-7343-40f0-b64d-c3354e029a87")]
        public string email_message
        {
            get { return _email_message; }
            set { _email_message = value; }
        }

        string _password_message;

        /// <summary>
        /// Gets or sets the value of variable password_message.
        /// </summary>
        [TestVariable("1e7922db-d4fa-4c4b-801b-e0f80e215796")]
        public string password_message
        {
            get { return _password_message; }
            set { _password_message = value; }
        }

        string _password_confirm_message;

        /// <summary>
        /// Gets or sets the value of variable password_confirm_message.
        /// </summary>
        [TestVariable("be9915be-21d1-41a5-ae1d-aaca406147eb")]
        public string password_confirm_message
        {
            get { return _password_confirm_message; }
            set { _password_confirm_message = value; }
        }

        string _username_message;

        /// <summary>
        /// Gets or sets the value of variable username_message.
        /// </summary>
        [TestVariable("b0e16a01-4988-470a-a1e8-6f63302ebef1")]
        public string username_message
        {
            get { return _username_message; }
            set { _username_message = value; }
        }

        string _tel_message;

        /// <summary>
        /// Gets or sets the value of variable tel_message.
        /// </summary>
        [TestVariable("4bbbe404-1166-4369-bceb-511b5fed8259")]
        public string tel_message
        {
            get { return _tel_message; }
            set { _tel_message = value; }
        }

        string _birthday_message;

        /// <summary>
        /// Gets or sets the value of variable birthday_message.
        /// </summary>
        [TestVariable("2d2b62b3-8599-4bd6-9083-880a0fc75e11")]
        public string birthday_message
        {
            get { return _birthday_message; }
            set { _birthday_message = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$email_message) on item 'Hotelサイト.Hotel_会員登録.メッセージ.label_メールアドレス_エラーメッセージ'.", repo.Hotelサイト.Hotel_会員登録.メッセージ.label_メールアドレス_エラーメッセージInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_会員登録.メッセージ.label_メールアドレス_エラーメッセージInfo, "InnerText", email_message, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$password_message) on item 'Hotelサイト.Hotel_会員登録.メッセージ.label_パスワード_エラーメッセージ'.", repo.Hotelサイト.Hotel_会員登録.メッセージ.label_パスワード_エラーメッセージInfo, new RecordItemIndex(1));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_会員登録.メッセージ.label_パスワード_エラーメッセージInfo, "InnerText", password_message, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$password_confirm_message) on item 'Hotelサイト.Hotel_会員登録.メッセージ.label_確認用パスワード_エラーメッセージ'.", repo.Hotelサイト.Hotel_会員登録.メッセージ.label_確認用パスワード_エラーメッセージInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_会員登録.メッセージ.label_確認用パスワード_エラーメッセージInfo, "InnerText", password_confirm_message, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$username_message) on item 'Hotelサイト.Hotel_会員登録.メッセージ.label_氏名_エラーメッセージ'.", repo.Hotelサイト.Hotel_会員登録.メッセージ.label_氏名_エラーメッセージInfo, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_会員登録.メッセージ.label_氏名_エラーメッセージInfo, "InnerText", username_message, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$tel_message) on item 'Hotelサイト.Hotel_会員登録.メッセージ.label_電話番号_エラーメッセージ'.", repo.Hotelサイト.Hotel_会員登録.メッセージ.label_電話番号_エラーメッセージInfo, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_会員登録.メッセージ.label_電話番号_エラーメッセージInfo, "InnerText", tel_message, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$birthday_message) on item 'Hotelサイト.Hotel_会員登録.メッセージ.label_生年月日_エラーメッセージ'.", repo.Hotelサイト.Hotel_会員登録.メッセージ.label_生年月日_エラーメッセージInfo, new RecordItemIndex(5));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_会員登録.メッセージ.label_生年月日_エラーメッセージInfo, "InnerText", birthday_message, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
