///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約_各プラン画面
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 操作_予約情報_入力 recording.
    /// </summary>
    [TestModule("c9b64694-ae17-4d56-9586-4f0a5638c552", ModuleType.Recording, 1)]
    public partial class 操作_予約情報_入力 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 操作_予約情報_入力 instance = new 操作_予約情報_入力();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 操作_予約情報_入力()
        {
            date = "";
            term = "";
            head_count = "";
            username = "";
            contact = "選択してください";
            tel = "";
            comment = "";
            breakfast = "";
            early_check_in = "";
            sightseeing = "";
            reserveEmail = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 操作_予約情報_入力 Instance
        {
            get { return instance; }
        }

#region Variables

        string _date;

        /// <summary>
        /// Gets or sets the value of variable date.
        /// </summary>
        [TestVariable("c02551c1-d266-4f83-bbff-e8c4ce722918")]
        public string date
        {
            get { return _date; }
            set { _date = value; }
        }

        string _term;

        /// <summary>
        /// Gets or sets the value of variable term.
        /// </summary>
        [TestVariable("20e9feb7-8772-4891-b361-62c515605770")]
        public string term
        {
            get { return _term; }
            set { _term = value; }
        }

        string _head_count;

        /// <summary>
        /// Gets or sets the value of variable head_count.
        /// </summary>
        [TestVariable("22425661-c3c2-418e-bbc7-f7b2ff3b611f")]
        public string head_count
        {
            get { return _head_count; }
            set { _head_count = value; }
        }

        string _tel;

        /// <summary>
        /// Gets or sets the value of variable tel.
        /// </summary>
        [TestVariable("4c2e263f-5815-45d6-a8b1-81feb36d53bb")]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        string _comment;

        /// <summary>
        /// Gets or sets the value of variable comment.
        /// </summary>
        [TestVariable("522de5de-7c57-42d6-be05-1dafc76c7762")]
        public string comment
        {
            get { return _comment; }
            set { _comment = value; }
        }

        string _breakfast;

        /// <summary>
        /// Gets or sets the value of variable breakfast.
        /// </summary>
        [TestVariable("c7f2b3cb-814f-45b1-a900-5752d9843af5")]
        public string breakfast
        {
            get { return _breakfast; }
            set { _breakfast = value; }
        }

        string _early_check_in;

        /// <summary>
        /// Gets or sets the value of variable early_check_in.
        /// </summary>
        [TestVariable("ec1b6cae-229f-448c-be50-0640813a6301")]
        public string early_check_in
        {
            get { return _early_check_in; }
            set { _early_check_in = value; }
        }

        string _sightseeing;

        /// <summary>
        /// Gets or sets the value of variable sightseeing.
        /// </summary>
        [TestVariable("e66aba5e-26e0-4454-8319-ea95e0035d54")]
        public string sightseeing
        {
            get { return _sightseeing; }
            set { _sightseeing = value; }
        }

        string _reserveEmail;

        /// <summary>
        /// Gets or sets the value of variable reserveEmail.
        /// </summary>
        [TestVariable("aa246211-4ac0-4ba2-9043-4ebaaa07b4ef")]
        public string reserveEmail
        {
            get { return _reserveEmail; }
            set { _reserveEmail = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable contact.
        /// </summary>
        [TestVariable("40f5a11f-8645-49d0-9cce-cd62192c946f")]
        public string contact
        {
            get { return repo.contact; }
            set { repo.contact = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("519022f2-2a81-4e13-8b89-748b5d51c5e0")]
        public string username
        {
            get { return repo.username; }
            set { repo.username = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_宿泊数Info, term);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_人数Info, head_count);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.checkbox_朝食バイキングInfo, breakfast);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.checkbox_昼からチェックインプランInfo, early_check_in);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.checkbox_お得な観光プランInfo, sightseeing);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_宿泊日Info, "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$date' with focus on 'Hotelサイト.Hotel_予約画面.予約情報入力.textbox_宿泊日'.", repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_宿泊日Info, new RecordItemIndex(6));
            repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_宿泊日.PressKeys(date);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名Info, "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$username' with focus on 'Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名'.", repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名Info, new RecordItemIndex(8));
            repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名.PressKeys(username);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'Hotelサイト.Hotel_予約画面.予約情報入力.option_確認のご連絡'.", repo.Hotelサイト.Hotel_予約画面.予約情報入力.option_確認のご連絡Info, new RecordItemIndex(9));
            repo.Hotelサイト.Hotel_予約画面.予約情報入力.option_確認のご連絡.Select();
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_メールアドレスInfo, reserveEmail);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_電話番号Info, tel);
            Delay.Milliseconds(0);
            
            UserCode.UserCodeCollection.InputIfIsNotIgnore(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textarea_ご要望Info, comment);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
