///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約_各プラン画面
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_宿泊予約画面_会員登録済み recording.
    /// </summary>
    [TestModule("3cc015c9-d19a-4605-babf-1247b4420f83", ModuleType.Recording, 1)]
    public partial class 確認_宿泊予約画面_会員登録済み : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_宿泊予約画面_会員登録済み instance = new 確認_宿泊予約画面_会員登録済み();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_宿泊予約画面_会員登録済み()
        {
            username = "";
            email = "";
            tel = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_宿泊予約画面_会員登録済み Instance
        {
            get { return instance; }
        }

#region Variables

        string _email;

        /// <summary>
        /// Gets or sets the value of variable email.
        /// </summary>
        [TestVariable("5a30ad02-7d64-4939-a601-481475bba61e")]
        public string email
        {
            get { return _email; }
            set { _email = value; }
        }

        string _tel;

        /// <summary>
        /// Gets or sets the value of variable tel.
        /// </summary>
        [TestVariable("a3d66c4a-2d7f-41ef-8b0e-92c35a67fc4f")]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("9979cabc-2051-43f3-9752-57a0be662545")]
        public string username
        {
            get { return repo.username; }
            set { repo.username = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Value=$username) on item 'Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名'.", repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名Info, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名Info, "Value", username, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Value=$email) on item 'Hotelサイト.Hotel_予約画面.予約情報入力.textbox_メールアドレス'.", repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_メールアドレスInfo, new RecordItemIndex(1));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_メールアドレスInfo, "Value", email, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Value=$tel) on item 'Hotelサイト.Hotel_予約画面.予約情報入力.textbox_電話番号'.", repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_電話番号Info, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_電話番号Info, "Value", tel, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
