///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約_各プラン画面
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_プラン名_詳細_表示 recording.
    /// </summary>
    [TestModule("9c542ffd-2f0b-4a32-a334-76a155268427", ModuleType.Recording, 1)]
    public partial class 確認_プラン名_詳細_表示 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_プラン名_詳細_表示 instance = new 確認_プラン名_詳細_表示();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_プラン名_詳細_表示()
        {
            plan_name = "";
            plan_desc = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_プラン名_詳細_表示 Instance
        {
            get { return instance; }
        }

#region Variables

        string _plan_name;

        /// <summary>
        /// Gets or sets the value of variable plan_name.
        /// </summary>
        [TestVariable("eb907e44-63cf-46e7-b3a4-8b4ed4620f2b")]
        public string plan_name
        {
            get { return _plan_name; }
            set { _plan_name = value; }
        }

        string _plan_desc;

        /// <summary>
        /// Gets or sets the value of variable plan_desc.
        /// </summary>
        [TestVariable("afa0b2df-3432-4350-bccf-533dae6eddef")]
        public string plan_desc
        {
            get { return _plan_desc; }
            set { _plan_desc = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'Hotelサイト.Hotel_予約画面'.", repo.Hotelサイト.Hotel_予約画面.SelfInfo, new RecordItemIndex(0));
                Validate.Exists(repo.Hotelサイト.Hotel_予約画面.SelfInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$plan_name) on item 'Hotelサイト.Hotel_予約画面.label_プラン名'.", repo.Hotelサイト.Hotel_予約画面.label_プラン名Info, new RecordItemIndex(1));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_プラン名Info, "InnerText", plan_name, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$plan_desc) on item 'Hotelサイト.Hotel_予約画面.label_プラン詳細'.", repo.Hotelサイト.Hotel_予約画面.label_プラン詳細Info, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_プラン詳細Info, "InnerText", plan_desc, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
