///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約_各プラン画面
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_宿泊予約画面_ゲスト会員 recording.
    /// </summary>
    [TestModule("8615b112-20c7-45cd-8452-721110e7c2d5", ModuleType.Recording, 1)]
    public partial class 確認_宿泊予約画面_ゲスト会員 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_宿泊予約画面_ゲスト会員 instance = new 確認_宿泊予約画面_ゲスト会員();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_宿泊予約画面_ゲスト会員()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_宿泊予約画面_ゲスト会員 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                UserCode.UserCodeCollection.ValidateTextboxesAreEmpty(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_氏名Info, "Value");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                UserCode.UserCodeCollection.ValidateTextboxesAreEmpty(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_メールアドレスInfo, "Value");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                UserCode.UserCodeCollection.ValidateTextboxesAreEmpty(repo.Hotelサイト.Hotel_予約画面.予約情報入力.textbox_電話番号Info, "Value");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
