///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約_各プラン画面
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_合計金額 recording.
    /// </summary>
    [TestModule("6f020ddf-898a-4db0-8e66-ffec42710e10", ModuleType.Recording, 1)]
    public partial class 確認_合計金額 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_合計金額 instance = new 確認_合計金額();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_合計金額()
        {
            total_bill = "9,375円";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_合計金額 Instance
        {
            get { return instance; }
        }

#region Variables

        string _total_bill;

        /// <summary>
        /// Gets or sets the value of variable total_bill.
        /// </summary>
        [TestVariable("85dde4f9-0c42-4b29-b2f6-499444b2e050")]
        public string total_bill
        {
            get { return _total_bill; }
            set { _total_bill = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (innertext=$total_bill) on item 'Hotelサイト.Hotel_予約画面.label_合計金額'.", repo.Hotelサイト.Hotel_予約画面.label_合計金額Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_合計金額Info, "innertext", total_bill);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
