///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約_各プラン画面
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_入力エラー検証 recording.
    /// </summary>
    [TestModule("d8297da6-4f81-41cf-aeae-3f0ceb8b0504", ModuleType.Recording, 1)]
    public partial class 確認_入力エラー検証 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_入力エラー検証 instance = new 確認_入力エラー検証();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_入力エラー検証()
        {
            dateMessage = "";
            termMessage = "";
            head_countMessage = "";
            usernameMessage = "";
            telMessage = "";
            emailMessage = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_入力エラー検証 Instance
        {
            get { return instance; }
        }

#region Variables

        string _dateMessage;

        /// <summary>
        /// Gets or sets the value of variable dateMessage.
        /// </summary>
        [TestVariable("337ff273-641c-49bb-bc9b-f139279fd210")]
        public string dateMessage
        {
            get { return _dateMessage; }
            set { _dateMessage = value; }
        }

        string _termMessage;

        /// <summary>
        /// Gets or sets the value of variable termMessage.
        /// </summary>
        [TestVariable("7b7fdba9-8a3d-45a7-9db5-2b09ee23d12a")]
        public string termMessage
        {
            get { return _termMessage; }
            set { _termMessage = value; }
        }

        string _head_countMessage;

        /// <summary>
        /// Gets or sets the value of variable head_countMessage.
        /// </summary>
        [TestVariable("3273c016-5f55-4cf1-a6ae-34fda6a2a16a")]
        public string head_countMessage
        {
            get { return _head_countMessage; }
            set { _head_countMessage = value; }
        }

        string _usernameMessage;

        /// <summary>
        /// Gets or sets the value of variable usernameMessage.
        /// </summary>
        [TestVariable("a8caade6-4886-443c-8480-1839b2e23fb0")]
        public string usernameMessage
        {
            get { return _usernameMessage; }
            set { _usernameMessage = value; }
        }

        string _telMessage;

        /// <summary>
        /// Gets or sets the value of variable telMessage.
        /// </summary>
        [TestVariable("9fa0e8d9-2c4f-44a7-b999-8b3245ba1883")]
        public string telMessage
        {
            get { return _telMessage; }
            set { _telMessage = value; }
        }

        string _emailMessage;

        /// <summary>
        /// Gets or sets the value of variable emailMessage.
        /// </summary>
        [TestVariable("fdbfd280-e69b-4715-971a-93fb3724159b")]
        public string emailMessage
        {
            get { return _emailMessage; }
            set { _emailMessage = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$dateMessage) on item 'Hotelサイト.Hotel_予約画面.label_宿泊日エラー'.", repo.Hotelサイト.Hotel_予約画面.label_宿泊日エラーInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_宿泊日エラーInfo, "InnerText", dateMessage, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$termMessage) on item 'Hotelサイト.Hotel_予約画面.label_宿泊数エラー'.", repo.Hotelサイト.Hotel_予約画面.label_宿泊数エラーInfo, new RecordItemIndex(1));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_宿泊数エラーInfo, "InnerText", termMessage, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$head_countMessage) on item 'Hotelサイト.Hotel_予約画面.label_人数エラー'.", repo.Hotelサイト.Hotel_予約画面.label_人数エラーInfo, new RecordItemIndex(2));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_人数エラーInfo, "InnerText", head_countMessage, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$usernameMessage) on item 'Hotelサイト.Hotel_予約画面.label_氏名エラー'.", repo.Hotelサイト.Hotel_予約画面.label_氏名エラーInfo, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_氏名エラーInfo, "InnerText", usernameMessage, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$telMessage) on item 'Hotelサイト.Hotel_予約画面.label_電話番号エラー'.", repo.Hotelサイト.Hotel_予約画面.label_電話番号エラーInfo, new RecordItemIndex(4));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_電話番号エラーInfo, "InnerText", telMessage, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$emailMessage) on item 'Hotelサイト.Hotel_予約画面.label_メールアドレスエラー'.", repo.Hotelサイト.Hotel_予約画面.label_メールアドレスエラーInfo, new RecordItemIndex(5));
                Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_メールアドレスエラーInfo, "InnerText", emailMessage, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
