///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HotelTrainingTest.Module.宿泊予約_各プラン画面
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 確認_各予約_合計金額 recording.
    /// </summary>
    [TestModule("d87e11fc-6da0-4b23-9b7f-d10859cd5a36", ModuleType.Recording, 1)]
    public partial class 確認_各予約_合計金額 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::HotelTrainingTest.Repository.Hotel_Planisphere repository.
        /// </summary>
        public static global::HotelTrainingTest.Repository.Hotel_Planisphere repo = global::HotelTrainingTest.Repository.Hotel_Planisphere.Instance;

        static 確認_各予約_合計金額 instance = new 確認_各予約_合計金額();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 確認_各予約_合計金額()
        {
            total_bill = "9,375円";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 確認_各予約_合計金額 Instance
        {
            get { return instance; }
        }

#region Variables

        string _total_bill;

        /// <summary>
        /// Gets or sets the value of variable total_bill.
        /// </summary>
        [TestVariable("43adc56d-a701-40f0-bf7a-ade2f784a8fe")]
        public string total_bill
        {
            get { return _total_bill; }
            set { _total_bill = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable planName.
        /// </summary>
        [TestVariable("42fe0e8d-57c7-4f5f-8af0-3bbf765a2da2")]
        public string planName
        {
            get { return repo.planName; }
            set { repo.planName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Hotelサイト.Hotel_宿泊予約.link_予約_可変名' at Center.", repo.Hotelサイト.Hotel_宿泊予約.link_予約_可変名Info, new RecordItemIndex(0));
            repo.Hotelサイト.Hotel_宿泊予約.link_予約_可変名.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded('1000ms') on item 'Hotelサイト.Hotel_予約画面'.", repo.Hotelサイト.Hotel_予約画面.SelfInfo, new RecordItemIndex(1));
            repo.Hotelサイト.Hotel_予約画面.Self.WaitForDocumentLoaded(ValueConverter.ArgumentFromString<Ranorex.Duration>("timeout", "1000ms"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (innertext=$total_bill) on item 'Hotelサイト.Hotel_予約画面.label_合計金額'.", repo.Hotelサイト.Hotel_予約画面.label_合計金額Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.Hotelサイト.Hotel_予約画面.label_合計金額Info, "innertext", total_bill);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'Hotelサイト.Hotel_予約画面'.", repo.Hotelサイト.Hotel_予約画面.SelfInfo, new RecordItemIndex(3));
            Host.Current.CloseApplication(repo.Hotelサイト.Hotel_予約画面.Self, new Duration(0));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
