///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace HotelTrainingTest.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Hotel_Planisphere element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("69c7490d-d614-4ebc-96f1-76f669a004c7")]
    public partial class Hotel_Planisphere : RepoGenBaseFolder
    {
        static Hotel_Planisphere instance = new Hotel_Planisphere();
        Hotel_PlanisphereFolders.RxDemoAppAppFolder _rxdemoapp;

        /// <summary>
        /// Gets the singleton class instance representing the Hotel_Planisphere element repository.
        /// </summary>
        [RepositoryFolder("69c7490d-d614-4ebc-96f1-76f669a004c7")]
        public static Hotel_Planisphere Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Hotel_Planisphere() 
            : base("Hotel_Planisphere", "/", null, 0, false, "69c7490d-d614-4ebc-96f1-76f669a004c7", ".\\RepositoryImages\\Hotel_Planisphere69c7490d.rximgres")
        {
            _rxdemoapp = new Hotel_PlanisphereFolders.RxDemoAppAppFolder(this);
        }

#region Variables

        string _username = "";

        /// <summary>
        /// Gets or sets the value of variable username.
        /// </summary>
        [TestVariable("f3af5798-8ccb-4256-b98b-1b043a7cc3e4")]
        public string username
        {
            get { return _username; }
            set { _username = value; }
        }

        string _planName = "";

        /// <summary>
        /// Gets or sets the value of variable planName.
        /// </summary>
        [TestVariable("42fe0e8d-57c7-4f5f-8af0-3bbf765a2da2")]
        public string planName
        {
            get { return _planName; }
            set { _planName = value; }
        }

        string _rank = "";

        /// <summary>
        /// Gets or sets the value of variable rank.
        /// </summary>
        [TestVariable("5c0ee3d3-01f4-499e-adfb-1e45d8d74ebe")]
        public string rank
        {
            get { return _rank; }
            set { _rank = value; }
        }

        string _contact = "";

        /// <summary>
        /// Gets or sets the value of variable contact.
        /// </summary>
        [TestVariable("71577ea4-975e-4349-a25f-4ad70fb1d22b")]
        public string contact
        {
            get { return _contact; }
            set { _contact = value; }
        }

        string _page = "";

        /// <summary>
        /// Gets or sets the value of variable page.
        /// </summary>
        [TestVariable("4c7c19c3-8b0d-414a-b6db-806518b096e7")]
        public string page
        {
            get { return _page; }
            set { _page = value; }
        }

        string _rowIndex = "";

        /// <summary>
        /// Gets or sets the value of variable rowIndex.
        /// </summary>
        [TestVariable("3ba6d22c-db6c-4b68-8a7d-a9909f8c81d4")]
        public string rowIndex
        {
            get { return _rowIndex; }
            set { _rowIndex = value; }
        }

        string _colIndex = "";

        /// <summary>
        /// Gets or sets the value of variable colIndex.
        /// </summary>
        [TestVariable("a7e7cbec-5c50-45a6-9942-0e6414418d5e")]
        public string colIndex
        {
            get { return _colIndex; }
            set { _colIndex = value; }
        }

        string _fileName = "";

        /// <summary>
        /// Gets or sets the value of variable fileName.
        /// </summary>
        [TestVariable("6ed3c54e-582c-4eb0-a18b-a83bc40af209")]
        public string fileName
        {
            get { return _fileName; }
            set { _fileName = value; }
        }

        string _gendetType = "";

        /// <summary>
        /// Gets or sets the value of variable gendetType.
        /// </summary>
        [TestVariable("b60cdcb5-f0e1-4aec-add6-f4908e26e84c")]
        public string gendetType
        {
            get { return _gendetType; }
            set { _gendetType = value; }
        }

        string _numberOfEntries = "";

        /// <summary>
        /// Gets or sets the value of variable numberOfEntries.
        /// </summary>
        [TestVariable("b479760e-30a2-4858-acba-f19e01086fa5")]
        public string numberOfEntries
        {
            get { return _numberOfEntries; }
            set { _numberOfEntries = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("69c7490d-d614-4ebc-96f1-76f669a004c7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxDemoApp folder.
        /// </summary>
        [RepositoryFolder("e86f8162-d366-4b3a-9e40-de4b790f55d6")]
        public virtual Hotel_PlanisphereFolders.RxDemoAppAppFolder RxDemoApp
        {
            get { return _rxdemoapp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Hotel_PlanisphereFolders
    {
        /// <summary>
        /// The RxDemoAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("e86f8162-d366-4b3a-9e40-de4b790f55d6")]
        public partial class RxDemoAppAppFolder : RepoGenBaseFolder
        {
            Hotel_PlanisphereFolders.タブ関連Folder _タブ関連;
            RepoItemInfo _button_exitInfo;

            /// <summary>
            /// Creates a new RxDemoApp  folder.
            /// </summary>
            public RxDemoAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxDemoApp", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, false, "e86f8162-d366-4b3a-9e40-de4b790f55d6", "")
            {
                _タブ関連 = new Hotel_PlanisphereFolders.タブ関連Folder(this);
                _button_exitInfo = new RepoItemInfo(this, "button_Exit", ".//button[@controlname='RxButtonExit']", "button[@controlname='RxButtonExit']", 30000, null, "ee513ff7-d790-4489-99f5-62de2b3ca094");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e86f8162-d366-4b3a-9e40-de4b790f55d6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e86f8162-d366-4b3a-9e40-de4b790f55d6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The button_Exit item.
            /// </summary>
            [RepositoryItem("ee513ff7-d790-4489-99f5-62de2b3ca094")]
            public virtual Ranorex.Button button_Exit
            {
                get
                {
                    return _button_exitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The button_Exit item info.
            /// </summary>
            [RepositoryItemInfo("ee513ff7-d790-4489-99f5-62de2b3ca094")]
            public virtual RepoItemInfo button_ExitInfo
            {
                get
                {
                    return _button_exitInfo;
                }
            }

            /// <summary>
            /// The タブ関連 folder.
            /// </summary>
            [RepositoryFolder("83e34caa-30c8-47bc-83d8-a3e0859a9e74")]
            public virtual Hotel_PlanisphereFolders.タブ関連Folder タブ関連
            {
                get { return _タブ関連; }
            }
        }

        /// <summary>
        /// The タブ関連Folder folder.
        /// </summary>
        [RepositoryFolder("83e34caa-30c8-47bc-83d8-a3e0859a9e74")]
        public partial class タブ関連Folder : RepoGenBaseFolder
        {
            Hotel_PlanisphereFolders.IntroductionタブFolder _introductionタブ;
            Hotel_PlanisphereFolders.Test_databaseタブFolder _test_databaseタブ;
            Hotel_PlanisphereFolders.Image_basedタブFolder _image_basedタブ;
            Hotel_PlanisphereFolders.UI_elementタブFolder _ui_elementタブ;
            Hotel_PlanisphereFolders.UploadタブFolder _uploadタブ;
            RepoItemInfo _tab_introductionInfo;
            RepoItemInfo _tab_test_databaseInfo;
            RepoItemInfo _tab_image_based_automationInfo;
            RepoItemInfo _tab_ui_element_test_areaInfo;
            RepoItemInfo _tab_upload_testingInfo;
            RepoItemInfo _tab_dynamic_idsInfo;
            RepoItemInfo _tab_object_identificationInfo;

            /// <summary>
            /// Creates a new タブ関連  folder.
            /// </summary>
            public タブ関連Folder(RepoGenBaseFolder parentFolder) :
                    base("タブ関連", ".//tabpagelist[@controlname='RxTabcontrol']", parentFolder, 30000, null, false, "83e34caa-30c8-47bc-83d8-a3e0859a9e74", "")
            {
                _introductionタブ = new Hotel_PlanisphereFolders.IntroductionタブFolder(this);
                _test_databaseタブ = new Hotel_PlanisphereFolders.Test_databaseタブFolder(this);
                _image_basedタブ = new Hotel_PlanisphereFolders.Image_basedタブFolder(this);
                _ui_elementタブ = new Hotel_PlanisphereFolders.UI_elementタブFolder(this);
                _uploadタブ = new Hotel_PlanisphereFolders.UploadタブFolder(this);
                _tab_introductionInfo = new RepoItemInfo(this, "tab_Introduction", "tabpage[@accessiblename='Introduction']", "", 30000, null, "bafed7c5-ca11-4943-af03-4d51571b012b");
                _tab_test_databaseInfo = new RepoItemInfo(this, "tab_Test_database", "tabpage[@accessiblename='Test database']", "", 30000, null, "d6e80eca-ae95-4351-aebb-e60e46ffd362");
                _tab_image_based_automationInfo = new RepoItemInfo(this, "tab_Image_based_automation", "tabpage[@accessiblename='Image-based automation']", "", 30000, null, "29f5c698-f66f-4ac0-b516-968163f09908");
                _tab_ui_element_test_areaInfo = new RepoItemInfo(this, "tab_UI_element_test_area", "tabpage[@accessiblename='UI-element test area']", "", 30000, null, "f98bb796-be14-4e20-943b-c76279e9a072");
                _tab_upload_testingInfo = new RepoItemInfo(this, "tab_Upload_testing", "tabpage[@accessiblename='Upload testing']", "", 30000, null, "34af1cf3-0f99-4628-9c14-46f20b33ab33");
                _tab_dynamic_idsInfo = new RepoItemInfo(this, "tab_Dynamic_IDs", "tabpage[@accessiblename='Dynamic IDs']", "", 30000, null, "e6c12e7d-060c-408a-a2f0-04fde8a97c13");
                _tab_object_identificationInfo = new RepoItemInfo(this, "tab_Object_identification", "tabpage[@accessiblename='Object identification']", "", 30000, null, "2b8c126d-878c-429e-b21c-387957f58066");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("83e34caa-30c8-47bc-83d8-a3e0859a9e74")]
            public virtual Ranorex.TabPageList Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("83e34caa-30c8-47bc-83d8-a3e0859a9e74")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The tab_Introduction item.
            /// </summary>
            [RepositoryItem("bafed7c5-ca11-4943-af03-4d51571b012b")]
            public virtual Ranorex.TabPage tab_Introduction
            {
                get
                {
                    return _tab_introductionInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tab_Introduction item info.
            /// </summary>
            [RepositoryItemInfo("bafed7c5-ca11-4943-af03-4d51571b012b")]
            public virtual RepoItemInfo tab_IntroductionInfo
            {
                get
                {
                    return _tab_introductionInfo;
                }
            }

            /// <summary>
            /// The tab_Test_database item.
            /// </summary>
            [RepositoryItem("d6e80eca-ae95-4351-aebb-e60e46ffd362")]
            public virtual Ranorex.TabPage tab_Test_database
            {
                get
                {
                    return _tab_test_databaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tab_Test_database item info.
            /// </summary>
            [RepositoryItemInfo("d6e80eca-ae95-4351-aebb-e60e46ffd362")]
            public virtual RepoItemInfo tab_Test_databaseInfo
            {
                get
                {
                    return _tab_test_databaseInfo;
                }
            }

            /// <summary>
            /// The tab_Image_based_automation item.
            /// </summary>
            [RepositoryItem("29f5c698-f66f-4ac0-b516-968163f09908")]
            public virtual Ranorex.TabPage tab_Image_based_automation
            {
                get
                {
                    return _tab_image_based_automationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tab_Image_based_automation item info.
            /// </summary>
            [RepositoryItemInfo("29f5c698-f66f-4ac0-b516-968163f09908")]
            public virtual RepoItemInfo tab_Image_based_automationInfo
            {
                get
                {
                    return _tab_image_based_automationInfo;
                }
            }

            /// <summary>
            /// The tab_UI_element_test_area item.
            /// </summary>
            [RepositoryItem("f98bb796-be14-4e20-943b-c76279e9a072")]
            public virtual Ranorex.TabPage tab_UI_element_test_area
            {
                get
                {
                    return _tab_ui_element_test_areaInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tab_UI_element_test_area item info.
            /// </summary>
            [RepositoryItemInfo("f98bb796-be14-4e20-943b-c76279e9a072")]
            public virtual RepoItemInfo tab_UI_element_test_areaInfo
            {
                get
                {
                    return _tab_ui_element_test_areaInfo;
                }
            }

            /// <summary>
            /// The tab_Upload_testing item.
            /// </summary>
            [RepositoryItem("34af1cf3-0f99-4628-9c14-46f20b33ab33")]
            public virtual Ranorex.TabPage tab_Upload_testing
            {
                get
                {
                    return _tab_upload_testingInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tab_Upload_testing item info.
            /// </summary>
            [RepositoryItemInfo("34af1cf3-0f99-4628-9c14-46f20b33ab33")]
            public virtual RepoItemInfo tab_Upload_testingInfo
            {
                get
                {
                    return _tab_upload_testingInfo;
                }
            }

            /// <summary>
            /// The tab_Dynamic_IDs item.
            /// </summary>
            [RepositoryItem("e6c12e7d-060c-408a-a2f0-04fde8a97c13")]
            public virtual Ranorex.TabPage tab_Dynamic_IDs
            {
                get
                {
                    return _tab_dynamic_idsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tab_Dynamic_IDs item info.
            /// </summary>
            [RepositoryItemInfo("e6c12e7d-060c-408a-a2f0-04fde8a97c13")]
            public virtual RepoItemInfo tab_Dynamic_IDsInfo
            {
                get
                {
                    return _tab_dynamic_idsInfo;
                }
            }

            /// <summary>
            /// The tab_Object_identification item.
            /// </summary>
            [RepositoryItem("2b8c126d-878c-429e-b21c-387957f58066")]
            public virtual Ranorex.TabPage tab_Object_identification
            {
                get
                {
                    return _tab_object_identificationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The tab_Object_identification item info.
            /// </summary>
            [RepositoryItemInfo("2b8c126d-878c-429e-b21c-387957f58066")]
            public virtual RepoItemInfo tab_Object_identificationInfo
            {
                get
                {
                    return _tab_object_identificationInfo;
                }
            }

            /// <summary>
            /// The Introductionタブ folder.
            /// </summary>
            [RepositoryFolder("9c04191d-3d83-4368-b2d7-8228c809d2d0")]
            public virtual Hotel_PlanisphereFolders.IntroductionタブFolder Introductionタブ
            {
                get { return _introductionタブ; }
            }

            /// <summary>
            /// The Test_databaseタブ folder.
            /// </summary>
            [RepositoryFolder("4c6e8e83-a7c0-46e5-bb1b-e3165ce68652")]
            public virtual Hotel_PlanisphereFolders.Test_databaseタブFolder Test_databaseタブ
            {
                get { return _test_databaseタブ; }
            }

            /// <summary>
            /// The Image_basedタブ folder.
            /// </summary>
            [RepositoryFolder("da005783-2ead-48fb-b2b4-ab7c4010a1da")]
            public virtual Hotel_PlanisphereFolders.Image_basedタブFolder Image_basedタブ
            {
                get { return _image_basedタブ; }
            }

            /// <summary>
            /// The UI_elementタブ folder.
            /// </summary>
            [RepositoryFolder("5d718375-9561-4fcd-ae60-09502b3c36ad")]
            public virtual Hotel_PlanisphereFolders.UI_elementタブFolder UI_elementタブ
            {
                get { return _ui_elementタブ; }
            }

            /// <summary>
            /// The Uploadタブ folder.
            /// </summary>
            [RepositoryFolder("3c9633fd-897f-4cba-894e-e18c794f4d12")]
            public virtual Hotel_PlanisphereFolders.UploadタブFolder Uploadタブ
            {
                get { return _uploadタブ; }
            }
        }

        /// <summary>
        /// The IntroductionタブFolder folder.
        /// </summary>
        [RepositoryFolder("9c04191d-3d83-4368-b2d7-8228c809d2d0")]
        public partial class IntroductionタブFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text_nameInfo;
            RepoItemInfo _label_welcomeInfo;
            RepoItemInfo _button_submitInfo;
            RepoItemInfo _link_resetInfo;

            /// <summary>
            /// Creates a new Introductionタブ  folder.
            /// </summary>
            public IntroductionタブFolder(RepoGenBaseFolder parentFolder) :
                    base("Introductionタブ", "tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "9c04191d-3d83-4368-b2d7-8228c809d2d0", "")
            {
                _text_nameInfo = new RepoItemInfo(this, "text_Name", ".//text[@accessiblename='Enter your name']", "", 30000, null, "aef9c2d4-c1e5-44d2-9bc1-1097c6a0cca3");
                _label_welcomeInfo = new RepoItemInfo(this, "label_Welcome", ".//text[@controlname='lblWelcomeMessage']", "", 30000, null, "b1f3fd65-5930-4016-92cc-75bbcaf49323");
                _button_submitInfo = new RepoItemInfo(this, "button_Submit", ".//button[@controlname='btnSubmitUserName']", "", 30000, null, "b5805b90-f4a7-4fef-b287-09c0080db5d8");
                _link_resetInfo = new RepoItemInfo(this, "link_Reset", ".//link[@accessiblename='Reset']", "", 30000, null, "b1033ebc-d77a-4eca-934b-a1e2617eb306");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c04191d-3d83-4368-b2d7-8228c809d2d0")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c04191d-3d83-4368-b2d7-8228c809d2d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The text_Name item.
            /// </summary>
            [RepositoryItem("aef9c2d4-c1e5-44d2-9bc1-1097c6a0cca3")]
            public virtual Ranorex.Text text_Name
            {
                get
                {
                    return _text_nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The text_Name item info.
            /// </summary>
            [RepositoryItemInfo("aef9c2d4-c1e5-44d2-9bc1-1097c6a0cca3")]
            public virtual RepoItemInfo text_NameInfo
            {
                get
                {
                    return _text_nameInfo;
                }
            }

            /// <summary>
            /// The label_Welcome item.
            /// </summary>
            [RepositoryItem("b1f3fd65-5930-4016-92cc-75bbcaf49323")]
            public virtual Ranorex.Text label_Welcome
            {
                get
                {
                    return _label_welcomeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The label_Welcome item info.
            /// </summary>
            [RepositoryItemInfo("b1f3fd65-5930-4016-92cc-75bbcaf49323")]
            public virtual RepoItemInfo label_WelcomeInfo
            {
                get
                {
                    return _label_welcomeInfo;
                }
            }

            /// <summary>
            /// The button_Submit item.
            /// </summary>
            [RepositoryItem("b5805b90-f4a7-4fef-b287-09c0080db5d8")]
            public virtual Ranorex.Button button_Submit
            {
                get
                {
                    return _button_submitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The button_Submit item info.
            /// </summary>
            [RepositoryItemInfo("b5805b90-f4a7-4fef-b287-09c0080db5d8")]
            public virtual RepoItemInfo button_SubmitInfo
            {
                get
                {
                    return _button_submitInfo;
                }
            }

            /// <summary>
            /// The link_Reset item.
            /// </summary>
            [RepositoryItem("b1033ebc-d77a-4eca-934b-a1e2617eb306")]
            public virtual Ranorex.Link link_Reset
            {
                get
                {
                    return _link_resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The link_Reset item info.
            /// </summary>
            [RepositoryItemInfo("b1033ebc-d77a-4eca-934b-a1e2617eb306")]
            public virtual RepoItemInfo link_ResetInfo
            {
                get
                {
                    return _link_resetInfo;
                }
            }
        }

        /// <summary>
        /// The Test_databaseタブFolder folder.
        /// </summary>
        [RepositoryFolder("4c6e8e83-a7c0-46e5-bb1b-e3165ce68652")]
        public partial class Test_databaseタブFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text_firstnameInfo;
            RepoItemInfo _text_lastnameInfo;
            RepoItemInfo _select_departmentInfo;
            RepoItemInfo _text_ageInfo;
            RepoItemInfo _radio_genderInfo;
            RepoItemInfo _button_add_entryInfo;
            RepoItemInfo _label_number_of_entriesInfo;
            RepoItemInfo _list_personlistInfo;
            RepoItemInfo _button_delete_entryInfo;

            /// <summary>
            /// Creates a new Test_databaseタブ  folder.
            /// </summary>
            public Test_databaseタブFolder(RepoGenBaseFolder parentFolder) :
                    base("Test_databaseタブ", "tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "4c6e8e83-a7c0-46e5-bb1b-e3165ce68652", "")
            {
                _text_firstnameInfo = new RepoItemInfo(this, "text_Firstname", ".//text[@controlname='txtFirstName']", "element", 30000, null, "65747c58-6289-411f-b861-6e1f880b974e");
                _text_lastnameInfo = new RepoItemInfo(this, "text_Lastname", ".//text[@controlname='txtLastName']", "element", 30000, null, "9057230a-9967-4feb-9403-77e2a63fdea1");
                _select_departmentInfo = new RepoItemInfo(this, "select_Department", ".//combobox[@controlname='cmbDepartment']", "element", 30000, null, "3979863f-21e9-430b-906e-478b6d3746e8");
                _text_ageInfo = new RepoItemInfo(this, "text_Age", ".//text[@controlname='upDownEdit']", "element", 30000, null, "293b025f-5b78-4e4b-9f41-0064c0f8c4a1");
                _radio_genderInfo = new RepoItemInfo(this, "radio_Gender", ".//radiobutton[@text=$gendetType]", "", 30000, null, "ec68ce38-e3bf-4fc5-8609-6171842ed57b");
                _button_add_entryInfo = new RepoItemInfo(this, "button_Add_entry", ".//button[@controlname='btnAddPerson']", "", 30000, null, "4a13cc4c-af45-4c62-9820-3cda57434742");
                _label_number_of_entriesInfo = new RepoItemInfo(this, "label_Number_of_entries", ".//text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "3254818c-8f51-492f-8a86-5315fabc2ee1");
                _list_personlistInfo = new RepoItemInfo(this, "list_PersonList", ".//list[@accessiblename=$numberOfEntries]/listitem", "", 30000, null, "c76e6d63-9f92-4920-b68e-0b1c8dd0d35a");
                _button_delete_entryInfo = new RepoItemInfo(this, "button_Delete_entry", ".//button[@controlname='btnDeletePerson']", "element", 30000, null, "142af4c3-9e5b-4299-b778-93f750339173");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4c6e8e83-a7c0-46e5-bb1b-e3165ce68652")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c6e8e83-a7c0-46e5-bb1b-e3165ce68652")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The text_Firstname item.
            /// </summary>
            [RepositoryItem("65747c58-6289-411f-b861-6e1f880b974e")]
            public virtual Ranorex.Text text_Firstname
            {
                get
                {
                    return _text_firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The text_Firstname item info.
            /// </summary>
            [RepositoryItemInfo("65747c58-6289-411f-b861-6e1f880b974e")]
            public virtual RepoItemInfo text_FirstnameInfo
            {
                get
                {
                    return _text_firstnameInfo;
                }
            }

            /// <summary>
            /// The text_Lastname item.
            /// </summary>
            [RepositoryItem("9057230a-9967-4feb-9403-77e2a63fdea1")]
            public virtual Ranorex.Text text_Lastname
            {
                get
                {
                    return _text_lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The text_Lastname item info.
            /// </summary>
            [RepositoryItemInfo("9057230a-9967-4feb-9403-77e2a63fdea1")]
            public virtual RepoItemInfo text_LastnameInfo
            {
                get
                {
                    return _text_lastnameInfo;
                }
            }

            /// <summary>
            /// The select_Department item.
            /// </summary>
            [RepositoryItem("3979863f-21e9-430b-906e-478b6d3746e8")]
            public virtual Ranorex.ComboBox select_Department
            {
                get
                {
                    return _select_departmentInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The select_Department item info.
            /// </summary>
            [RepositoryItemInfo("3979863f-21e9-430b-906e-478b6d3746e8")]
            public virtual RepoItemInfo select_DepartmentInfo
            {
                get
                {
                    return _select_departmentInfo;
                }
            }

            /// <summary>
            /// The text_Age item.
            /// </summary>
            [RepositoryItem("293b025f-5b78-4e4b-9f41-0064c0f8c4a1")]
            public virtual Ranorex.Text text_Age
            {
                get
                {
                    return _text_ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The text_Age item info.
            /// </summary>
            [RepositoryItemInfo("293b025f-5b78-4e4b-9f41-0064c0f8c4a1")]
            public virtual RepoItemInfo text_AgeInfo
            {
                get
                {
                    return _text_ageInfo;
                }
            }

            /// <summary>
            /// The radio_Gender item.
            /// </summary>
            [RepositoryItem("ec68ce38-e3bf-4fc5-8609-6171842ed57b")]
            public virtual Ranorex.RadioButton radio_Gender
            {
                get
                {
                    return _radio_genderInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The radio_Gender item info.
            /// </summary>
            [RepositoryItemInfo("ec68ce38-e3bf-4fc5-8609-6171842ed57b")]
            public virtual RepoItemInfo radio_GenderInfo
            {
                get
                {
                    return _radio_genderInfo;
                }
            }

            /// <summary>
            /// The button_Add_entry item.
            /// </summary>
            [RepositoryItem("4a13cc4c-af45-4c62-9820-3cda57434742")]
            public virtual Ranorex.Button button_Add_entry
            {
                get
                {
                    return _button_add_entryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The button_Add_entry item info.
            /// </summary>
            [RepositoryItemInfo("4a13cc4c-af45-4c62-9820-3cda57434742")]
            public virtual RepoItemInfo button_Add_entryInfo
            {
                get
                {
                    return _button_add_entryInfo;
                }
            }

            /// <summary>
            /// The label_Number_of_entries item.
            /// </summary>
            [RepositoryItem("3254818c-8f51-492f-8a86-5315fabc2ee1")]
            public virtual Ranorex.Text label_Number_of_entries
            {
                get
                {
                    return _label_number_of_entriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The label_Number_of_entries item info.
            /// </summary>
            [RepositoryItemInfo("3254818c-8f51-492f-8a86-5315fabc2ee1")]
            public virtual RepoItemInfo label_Number_of_entriesInfo
            {
                get
                {
                    return _label_number_of_entriesInfo;
                }
            }

            /// <summary>
            /// The list_PersonList item.
            /// </summary>
            [RepositoryItem("c76e6d63-9f92-4920-b68e-0b1c8dd0d35a")]
            public virtual Ranorex.ListItem list_PersonList
            {
                get
                {
                    return _list_personlistInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The list_PersonList item info.
            /// </summary>
            [RepositoryItemInfo("c76e6d63-9f92-4920-b68e-0b1c8dd0d35a")]
            public virtual RepoItemInfo list_PersonListInfo
            {
                get
                {
                    return _list_personlistInfo;
                }
            }

            /// <summary>
            /// The button_Delete_entry item.
            /// </summary>
            [RepositoryItem("142af4c3-9e5b-4299-b778-93f750339173")]
            public virtual Ranorex.Button button_Delete_entry
            {
                get
                {
                    return _button_delete_entryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The button_Delete_entry item info.
            /// </summary>
            [RepositoryItemInfo("142af4c3-9e5b-4299-b778-93f750339173")]
            public virtual RepoItemInfo button_Delete_entryInfo
            {
                get
                {
                    return _button_delete_entryInfo;
                }
            }
        }

        /// <summary>
        /// The Image_basedタブFolder folder.
        /// </summary>
        [RepositoryFolder("da005783-2ead-48fb-b2b4-ab7c4010a1da")]
        public partial class Image_basedタブFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkbox_show_imageInfo;
            RepoItemInfo _img_catInfo;
            RepoItemInfo _calendarInfo;

            /// <summary>
            /// Creates a new Image_basedタブ  folder.
            /// </summary>
            public Image_basedタブFolder(RepoGenBaseFolder parentFolder) :
                    base("Image_basedタブ", "tabpage[@controlname='RxTabImageBased']", parentFolder, 30000, null, false, "da005783-2ead-48fb-b2b4-ab7c4010a1da", "")
            {
                _checkbox_show_imageInfo = new RepoItemInfo(this, "checkbox_show_image", ".//checkbox[@text='Show image']", "", 30000, null, "11056a6b-d423-4e52-adae-9fc90f1fe5a9");
                _img_catInfo = new RepoItemInfo(this, "img_cat", ".//picture[@controlname='TheCat']", "", 30000, null, "9d3e9c03-938c-4c48-ae71-fa44b2af256a");
                _calendarInfo = new RepoItemInfo(this, "calendar", ".//datetime[@controlname='monthCalendar1']", "", 30000, null, "ae14371d-06e4-41b7-aa27-494d1c53cdcb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("da005783-2ead-48fb-b2b4-ab7c4010a1da")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("da005783-2ead-48fb-b2b4-ab7c4010a1da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The checkbox_show_image item.
            /// </summary>
            [RepositoryItem("11056a6b-d423-4e52-adae-9fc90f1fe5a9")]
            public virtual Ranorex.CheckBox checkbox_show_image
            {
                get
                {
                    return _checkbox_show_imageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The checkbox_show_image item info.
            /// </summary>
            [RepositoryItemInfo("11056a6b-d423-4e52-adae-9fc90f1fe5a9")]
            public virtual RepoItemInfo checkbox_show_imageInfo
            {
                get
                {
                    return _checkbox_show_imageInfo;
                }
            }

            /// <summary>
            /// The img_cat item.
            /// </summary>
            [RepositoryItem("9d3e9c03-938c-4c48-ae71-fa44b2af256a")]
            public virtual Ranorex.Picture img_cat
            {
                get
                {
                    return _img_catInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The img_cat item info.
            /// </summary>
            [RepositoryItemInfo("9d3e9c03-938c-4c48-ae71-fa44b2af256a")]
            public virtual RepoItemInfo img_catInfo
            {
                get
                {
                    return _img_catInfo;
                }
            }

            /// <summary>
            /// The calendar item.
            /// </summary>
            [RepositoryItem("ae14371d-06e4-41b7-aa27-494d1c53cdcb")]
            public virtual Ranorex.DateTime calendar
            {
                get
                {
                    return _calendarInfo.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The calendar item info.
            /// </summary>
            [RepositoryItemInfo("ae14371d-06e4-41b7-aa27-494d1c53cdcb")]
            public virtual RepoItemInfo calendarInfo
            {
                get
                {
                    return _calendarInfo;
                }
            }
        }

        /// <summary>
        /// The UI_elementタブFolder folder.
        /// </summary>
        [RepositoryFolder("5d718375-9561-4fcd-ae60-09502b3c36ad")]
        public partial class UI_elementタブFolder : RepoGenBaseFolder
        {
            RepoItemInfo _table_除外領域Info;

            /// <summary>
            /// Creates a new UI_elementタブ  folder.
            /// </summary>
            public UI_elementタブFolder(RepoGenBaseFolder parentFolder) :
                    base("UI_elementタブ", "tabpage[@controlname='RxTabUIElements']", parentFolder, 30000, null, false, "5d718375-9561-4fcd-ae60-09502b3c36ad", "")
            {
                _table_除外領域Info = new RepoItemInfo(this, "table_除外領域", ".//table[@controlname='dataGridView1']/row[$rowIndex]/cell[$colIndex]", "", 30000, null, "f4bd3677-8687-4e10-92af-b895c4106224");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5d718375-9561-4fcd-ae60-09502b3c36ad")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5d718375-9561-4fcd-ae60-09502b3c36ad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The table_除外領域 item.
            /// </summary>
            [RepositoryItem("f4bd3677-8687-4e10-92af-b895c4106224")]
            public virtual Ranorex.Cell table_除外領域
            {
                get
                {
                    return _table_除外領域Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The table_除外領域 item info.
            /// </summary>
            [RepositoryItemInfo("f4bd3677-8687-4e10-92af-b895c4106224")]
            public virtual RepoItemInfo table_除外領域Info
            {
                get
                {
                    return _table_除外領域Info;
                }
            }
        }

        /// <summary>
        /// The UploadタブFolder folder.
        /// </summary>
        [RepositoryFolder("3c9633fd-897f-4cba-894e-e18c794f4d12")]
        public partial class UploadタブFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button_start_file_uploadInfo;
            RepoItemInfo _label_progresspercentInfo;

            /// <summary>
            /// Creates a new Uploadタブ  folder.
            /// </summary>
            public UploadタブFolder(RepoGenBaseFolder parentFolder) :
                    base("Uploadタブ", "tabpage[@controlname='RxTabUpload']", parentFolder, 30000, null, false, "3c9633fd-897f-4cba-894e-e18c794f4d12", "")
            {
                _button_start_file_uploadInfo = new RepoItemInfo(this, "button_Start_file_upload", ".//button[@controlname='btnStartUpload']", "", 30000, null, "6847661f-52e9-443a-a3f9-d79c5b11eaba");
                _label_progresspercentInfo = new RepoItemInfo(this, "label_progressPercent", ".//text[@controlname='lblCounter']", "", 30000, null, "93409120-6de9-4e10-a5f1-23714e65a8f1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3c9633fd-897f-4cba-894e-e18c794f4d12")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3c9633fd-897f-4cba-894e-e18c794f4d12")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The button_Start_file_upload item.
            /// </summary>
            [RepositoryItem("6847661f-52e9-443a-a3f9-d79c5b11eaba")]
            public virtual Ranorex.Button button_Start_file_upload
            {
                get
                {
                    return _button_start_file_uploadInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The button_Start_file_upload item info.
            /// </summary>
            [RepositoryItemInfo("6847661f-52e9-443a-a3f9-d79c5b11eaba")]
            public virtual RepoItemInfo button_Start_file_uploadInfo
            {
                get
                {
                    return _button_start_file_uploadInfo;
                }
            }

            /// <summary>
            /// The label_progressPercent item.
            /// </summary>
            [RepositoryItem("93409120-6de9-4e10-a5f1-23714e65a8f1")]
            public virtual Ranorex.Text label_progressPercent
            {
                get
                {
                    return _label_progresspercentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The label_progressPercent item info.
            /// </summary>
            [RepositoryItemInfo("93409120-6de9-4e10-a5f1-23714e65a8f1")]
            public virtual RepoItemInfo label_progressPercentInfo
            {
                get
                {
                    return _label_progresspercentInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
